### ISSUE TITLE
one to many asymmetric enc? 

### ISSUE THREAD

**Issue by amityahav** [ibarrond/Pyfhel#109]
Hey there , i have 2 questions:

1. Do you support one to many asymmetric enc? meaning one public key and N secret keys which will decrypt the msg that was encrypted with the sole public key?
2. Do you support 2D numpy arrays encryptions?

**Comment by ibarrond** [comment]
Hi @amityahav first of all my apologies for the delay! December was a busy month.

1. We do not. If you wish to have this functionality, I strongly suggest you to take a look at https://github.com/ldsec/lattigo as an alternative. Beware! it is written in Golang!
2. Not yet, but it is one of the improvements I have in mind for the library.
