### ISSUE TITLE
HE.savepublicKey(pk_file) -- AttributeError: 'Pyfhel.Pyfhel.Pyfhel' object has no attribute 'savepublicKey'

### ISSUE THREAD

**Issue by coderhard** [ibarrond/Pyfhel#114]
**Description**
Dev branch throwing runtime error when encountering savepublicKey() method.

When attempting to use the [Client Server Demo code](https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_ClientServer.py) in Juoyter notebook, there is a point where we need to save the public key. When attempted, the following error is thrown:

AttributeError: 'Pyfhel.Pyfhel.Pyfhel' object has no attribute 'savepublicKey'

**Code To Reproduce Error**
```
HE = Pyfhel()
HE.contextGen("bfv", p=65537,  n=2**12,  p_bits=0, sec=256)
HE.keyGen() # Generates both a public and a private key
# Saving only the public key and the context
HE.savepublicKey(pk_file) 
```
**Threw this exception**
```
AttributeError                            Traceback (most recent call last)
Input In [4], in <module>
     22 HE.keyGen() # Generates both a public and a private key
     24 # Saving only the public key and the context
---> 25 HE.savepublicKey(pk_file)
     26 HE.saveContext(contx_file)
     28 # Serializing two float values

AttributeError: 'Pyfhel.Pyfhel.Pyfhel' object has no attribute 'savepublicKey'
```

**Expected behavior**
The public key file was supposed to be saved. At least it was saved when using the main branch code.

**Setup:**
 - **OS**: Linux _hostname_ 5.10.16.3-microsoft-standard-WSL2 x86_64 x86_64 x86_64 GNU/Linux
 - **Python**: Python 3.9.9
 - **C compiler version**: GCC 9.4.0
 - **Pyfhel Version**: 3.0.1

1.  Setup a separate environment to prevent stepping on other versions for other projects
`conda create --name pyfhel pandas numpy matplotlib scikit-learn jupyter seaborn
`
2.  Change into that conda environment
`conda activate pyfhel
`
3.  Clone from the dev branch... since that's the one that has the fixes to SEAL and palisade
`git clone --branch dev --recursive https://github.com/ibarrond/Pyfhel.git
`
4.  Change into the now cloned directory
`cd Pyfhel/
`
5.  Use pip to install in this local environment from this directory
`pip install .
`
6.  Launch Jupyter Notebook and load the Client Server Demo ipnyb file
`jupyter notebook`

**Comment by ibarrond** [comment]
Apologies for the very late reply! the function has been migrated to `HE.save_public_key`, and the demos have been updated accordingly
