### ISSUE TITLE
How to [feature]?

### ISSUE THREAD

**Issue by pchandr3** [ibarrond/Pyfhel#115]
I've been having issues with understanding the ciphertext data objects. 

I have been comparing the two ciphertexts of the same integer and they are both different. I can't seem to find which part of the ciphertext object contains the encrypted number and which part contains additional information.

For example -

HE = Pyfhel()                                       
HE.contextGen(p=65537, m=2048, base=3)  

HE.keyGen()

int1 = 5
int2 = 5
int3 = 6

c1 = HE.encryptInt(int1)
c2 = HE.encryptInt(int2)

I'm not sure which part of the variable C1 and which part of the variable C2 should be the same. Or have I missed something here? I'm a bit new to this, so I appreciate your help!

Thank you!

**Comment by AlexanderViand** [comment]
For security, each encryption uses some new randomness (this is the case in pretty much all public-key encryption schemes), so two encryptions of 5 are no more alike than encryptions of 5 and 6 would be. Beyond some basic "housekeeping" information, virtually all of the ciphertexts will be just encrypted "stuff" that can't be meaningfully compared.

In `PyCtxt`,  only [these three fields](https://github.com/ibarrond/Pyfhel/blob/dev/Pyfhel/PyCtxt.pxd#L22-L24) should be the same for (compatible) ciphertexts, with pretty much all the information stored inside the `AfCtxt`. This (or, rather, the concrete `AfSealCtxt`) class is just a wrapper around a `seal::Ciphertext`, and that contains some parameter information (which is more-or-less the same for compatible ciphertexts) and a pointer into SEAL's memory pool where the actual polynomials (encrypted data) is stored.

**Comment by pchandr3** [comment]
Hi Alexander,

Thank you for responding. This might be a question that’s out of scope here - but can you suggest a method that I can use to compare cipher texts?

Thank you,
-Prasanna

**Comment by AlexanderViand** [comment]
There isn't really a meaningful way to compare Ciphertexts, but there are ways to compute the comparison function over the values encrypted inside, returning a ciphertext that contains the boolean result. 

However, this is not trivial as it requires either very clever math to compute the comparison using only addition and multiplication operations (the native operations available in FHE schemes) or by encrypting inputs bit-wise (one ctxt per bit of the input) and computing the function in the same way a comparator circuit would do it.

**Comment by pchandr3** [comment]
Alexander,

Thank you so much for your detailed response! Would you be able to point me toward a resource that might be able to help me understand this in greater detail?

My end goal is to build a sensor (like a thermometer for example) that can pass an alarm when it goes over a certain number - except that number is encrypted. The sensor outputs are encrypted and it then compares it to the threshold value, which is encrypted to begin with.

I hope my question makes sense and I'm happy to ask in a different forum if that's more appropriate.

Thank you!

------- Original Message -------

**Comment by AlexanderViand** [comment]
I don't think your example will work with FHE: If a value is encrypted, we can compute a new ciphertext that contains 0 if the value is under the threshold and 1 if above, but the result is still encrypted and no-one except the secret key owner can determine which it is, so no-one except the secret key owner could trigger an alarm. But if you've got access to the secret key, you wouldn't need to compute the threshold homomorphically, you could just decrypt and do it on the decrypted value.

I think you might be looking for something like *functional encryption*, where the output of the function becomes public. However, afaik nobody has managed to implement secure & practical functional encryption yet.
