### ISSUE TITLE
How can I know more about p and m?

### ISSUE THREAD

**Issue by EchizenG** [ibarrond/Pyfhel#117]
**Describe the feature**
Recently, I was trying to fine-tune the **p** and **m** in contextGen. But I have no idea about how it works. Could you please offer some papers relating to this hyperparameter and how HE works? Thanks!

**Comment by AlexanderViand** [comment]
There's sadly no "easy" way to learn how to manually set FHE parameters, but here are some ressources that might be helpful:
* [SEAL Manual 2.3.1](https://www.microsoft.com/en-us/research/uploads/prod/2017/11/sealmanual-2-3-1.pdf). This is for a _very_ outdated version of SEAL, but a lot of the basic cryptographic concepts they introduce haven't really changed, even if we are now on version 4.0.0 or similar
* [Homomorphic Encryption for Arithmetic of Approximate Numbers](https://eprint.iacr.org/2016/421.pdf). This is the original paper that describes CKKS.
* [Fully Homomorphic Encryption without Modulus Switching from Classical GapSVP](https://eprint.iacr.org/2012/078) and [Somewhat Practical Fully Homomorphic Encryption](https://eprint.iacr.org/2012/144). These are the papers that describe the B/FV scheme. 
* [Parameter Selection in Ring-LWE-based Fully Homomorphic Encryption](https://malb.io/discrete-subgroup/slides/2017-09-29-player.pdf). Sadly just a slide deck (I don't think the talk was recorded), but it goes into the exact topic.
* [Homomorphic Encryption Standard](https://homomorphicencryption.org/standard/). This is currently the most "official" recommendation for what parameter combinations are considered safe, until the ISO standard on FHE is released.

**Comment by EchizenG** [comment]
Thank you so much!

**Comment by ShokofehVS** [comment]
Hi!

I have set the setup and parameters like this:
`HE.contextGen(p=1964769281, m=8192,sec=192, flagBatching=True, base=2, intDigits=64, fracDigits=4096`
print(he.getp()) ->plaintext modulus -> 1964769281 
print(he.getm()) ->polynomial degree -> 8192
print(he.getflagBatch()) ->true 
print(he.getbase()) ->2
print(he.getnSlots()) -> 8192
print(he.getintDigits())->64
print(he.getfracDigits())->4096
print(he.getsec())->192

I would like to ask if m=8192 and log q = 192-bit setting 192-bit security level is correct based on the homomorphic encryption standard (http://homomorphicencryption.org/wp-content/uploads/2018/11/HomomorphicEncryptionStandardv1.1.pdf) or against the LWE hardness estimator (https://lwe-estimator.readthedocs.io/en/latest/).

**Comment by ibarrond** [comment]
The security level ensures q high enough to comply with the
homomorphicencryption standard for that equivalent bits of security.

**Comment by ShokofehVS** [comment]
Thank you for your response.
