### ISSUE TITLE
relinKeyGen does not work

### ISSUE THREAD

**Issue by alltootechnical** [ibarrond/Pyfhel#12]
Before I can exponentiate a ciphertext using the `power` function, I need to generate a relinearization key. But after invoking `relinKeyGen` and then using `power`, I still get the error message:
`RuntimeError: Relinearization key not initialized`

It seems that the culprit may be in the following line:
https://github.com/ibarrond/Pyfhel/blob/177c3531e4f76f55e36c798ef63eab373fc7b8d8/Pyfhel/Pyfhel.pyx#L527

**Comment by ibarrond** [comment]
Thanks! It is now changed! I will update the PyPi version tomorrow.

**Comment by alltootechnical** [comment]
It's working now, thanks!
