### ISSUE TITLE
make: *** [Makefile:20: html] Error 2

### ISSUE THREAD

**Issue by coderhard** [ibarrond/Pyfhel#121]
**Description**
I tried to generate docs for Pyfhel but the build failed. I first installed sphinx (pip install -r docs/requirements.txt). Then I cd'd into docs and tried to make html. This produced an error. And it did not build any documentation.

**Code To Reproduce Error**
(1pyfhel) 00000@myhost:~/projects/1pyfhel/Pyfhel$ cd docs
(1pyfhel) 00000@myhost:~/projects/1pyfhel/Pyfhel/docs$ make html
Running Sphinx v4.5.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/00000/miniconda3/envs/1pyfhel/lib/python3.9/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/mnt/c/Users/1111/projects/1pyfhel/Pyfhel/docs/conf.py", line 26, in <module>
    import Pyfhel
  File "/home/00000/miniconda3/envs/1pyfhel/lib/python3.9/site-packages/Pyfhel/__init__.py", line 1, in <module>
    from .Pyfhel import Pyfhel
  File "Pyfhel/Pyfhel.pyx", line 1, in init Pyfhel.Pyfhel
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 232 from C header, got 216 from PyObject

make: *** [Makefile:20: html] Error 2

**Expected behavior**
I expected html-ified documentation to be built

**Setup:**
 - OS: Linux myhost 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Python: 3.9.7
 - C compiler version: GCC 7.5.0
 - Pyfhel Version: v2.3.1

**Comment by ibarrond** [comment]
Please retry with `Pyfelh=3.1.1`, I just ran the docs generation and it worked correctly.

**Comment by ibarrond** [comment]
I confirm the docs now compile correctly! Check http://pyfhel.readthedocs.io/
