### ISSUE TITLE
Installing Pyfhel on Rocky Linux:  "error: command 'gcc' failed with exit status 1"

### ISSUE THREAD

**Issue by ShokofehVS** [ibarrond/Pyfhel#129]
**Description**
Pyfhel Installation on Rocky Linux gets an error:
`   Pyfhel/Pyfhel.cpp:41:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-nmcx3c_e/Pyfhel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-c8_f7zkj-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-nmcx3c_e/Pyfhel/`

**Setup:**
 - OS: Rocky Linux 8.6
 - Python: 3.8.12
 - C compiler version: gcc (GCC) 8.5.0 
 - Pyfhel Version: 2.3.1 and 3.1.4

**Comment by ibarrond** [comment]
You should use the package manager of your rocky Linux to install the dev package of Python. (in Debian/Ubuntu you run `apt-get install python3-dev`)

**Comment by ShokofehVS** [comment]
Thank you! yes, now it is installed properly.
