### ISSUE TITLE
Installation with pip : "ModuleNotFoundError: No module named 'numpy'"

### ISSUE THREAD

**Issue by Walz** [ibarrond/Pyfhel#13]
Hello,

When installing Pyfhel with pip I got the following error : 
```
Collecting Pyfhel
  Downloading https://files.pythonhosted.org/packages/36/ff/dddccc7f782acb14f62f2cd66bf54b90269fd7a30e9771a1378df2ffca9a/Pyfhel-2.0.0a4.tar.gz (745kB)
    100% |████████████████████████████████| 747kB 2.8MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-e3lbn659/Pyfhel/setup.py", line 7, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-e3lbn659/Pyfhel/
```

I think, it means that numpy should be moved from `install_requires` to `setup_requires` in [setup.py](https://github.com/ibarrond/Pyfhel/blob/master/setup.py).

**Comment by ibarrond** [comment]
You're right! It is also required in the package (thus I'm leaving it in the `install_requires`), but I added it to the setup_requires. It is wonderful to have such short errors with such clearly proposed solutions. Thanks!

https://github.com/ibarrond/Pyfhel/commit/69dd3ae506fe2bede1127c5ac6065160e6ed37f0

**Comment by ibarrond** [comment]
Clossing the issue, since both the `setup.py` and the newly created `requirements.txt` include numpy.
