### ISSUE TITLE
align_mod_n_scale before multiply

### ISSUE THREAD

**Issue by meirgold** [ibarrond/Pyfhel#145]
Hi,

Looking at the CKKS example in the library (Demo_3_Float_CKKS.py) in section 5: Rescaling & Mod Switching, I tried to simulate an issue I am seeing in my real code,
Before the `print("\n5. Rescaling & Mod Switching.")`  I added: `test = c_mse_1 * c_mean`
This causes the multiplication of 2 ciphertexts with different mod levels. c_mse_1 has mod_level=2 and c_mean has mod_level=1
The documentation states that:
    # To ease the life of the user, Pyfhel provides `HE.align_mod_n_scale(this, other)`,
    # which automatically does the rescaling and mod switching. All the 2-input
    # overloaded operators (+, -, \*, /) of PyCtxt automatically call this function.
    # The respective HE.add, HE.sub, HE.multiply don't.

So, I would have expected this multiplication operation to succeed, however, it failed with the following error:
File "Pyfhel/PyCtxt.pyx", line 437, in Pyfhel.PyCtxt.PyCtxt.__mul__
  File "Pyfhel/Pyfhel.pyx", line 1016, in Pyfhel.Pyfhel.Pyfhel.multiply
ValueError: encrypted1 and encrypted2 parameter mismatch

I decided to manually call the HE.align_mod_n_scale function before multiplying as following:
HE.align_mod_n_scale(c_mse_1, c_mean)
test = c_mse_1 * c_mean
But this failed with the same error.

The onlyway to resolve the issue was to call `HE.rescale_to_next(c_mean)` before the multiplication.

My questions are as following:
1. How come the call to align_mod_n_scale did not resolve the issue? 
2. It seems that in my code I need to keep track of the mod_level of each ciphertext in orde to know when to rescale it. Is there a way to check the mod_level using code? Do you have a different suggestion for handling these issues at runtime?

Thanks,

Meir

**Comment by meirgold** [comment]
Just noticed that  align_mod_n_scale returns a tuple. While this is documented on the website, the code decleration says that it returns None:

    def align_mod_n_scale(self, PyCtxt_this, other, PyCtxt=None, PyPtxt=None, *args, **kwargs): # real signature unknown; NOTE: unreliably restored from __doc__ 
        """
        Pyfhel.align_mod_n_scale(self, PyCtxt this: PyCtxt, other: Union[PyCtxt, PyPtxt], bool copy_this: bool = True, bool copy_other: bool = True) -> Tuple[PyCtxt, Union[PyCtxt, PyPtxt]]
        Aligns the scales & mod_levels of `this` and `other`.
                
                Only applies to CKKS. Alligns the scales of the `this` ciphertext and
                the `other` ciphertext/plaintext by aligning the scale and mod_level:
                - Rescales the ciphertext with the highest mod_level to the next qi/s 
                - Mod switches the second ciphertext/plaintext to the next qi/s
                - At the end, rounds the scale of the rescaled ciphertext
        
                Arguments:
                    this (PyCtxt): Ciphertext to align.
                    other (PyCtxt|PyPtxt): Ciphertext|plaintext to align with.
                    
                Return:
                    None
        """

This is what confused me and now it works for me.
Still I'm interested to know how come this did not get executed automatically during multiply

**Comment by ibarrond** [comment]
Related to #128, it was an existing bug that should now be fixed (as per v3.3.0, [5e0a456](https://github.com/ibarrond/Pyfhel/commit/5e0a456050a02f6d79d995d4d224aee688d31cb6)).

The `align_mod_n_scale` function is now properly documented. Thanks for noticing!

https://github.com/ibarrond/Pyfhel/blob/5e0a456050a02f6d79d995d4d224aee688d31cb6/Pyfhel/Pyfhel.pyx#L1336-L1337

Please reopen if the issue persists somehow, and in that case provide a short piece of code to run and reproduce in our side.

Closing!
