### ISSUE TITLE
Arithmetic actions with very large numbers in CKKS

### ISSUE THREAD

**Issue by meirgold** [ibarrond/Pyfhel#146]
Hi,

I'm not sure if this is a pyfhel or SEAL related issue, but I hope you can answer this anyway.
I need to perform arithmetic operations (addition, multiplication) using very large numbers before the decimal point. I assume that I  will reqreuire at least 50 or 60 bits of representation to start with, maybe even more for later operations.

AFAIK, the number of bits used to represent the numbers before the decimal point in a CKKS ciphertext is the difference between the largest number to the lower ones in qi, so if I define my qi as: [60, 30, 30, 30, 60], I will have 60-30=30bits of number representation.
I also noticed that pyfhel does not support qi numbers larger than 60 or lower than 25. 
Is there any way to squeeze some more bits out of ckks for large number representation?

**Comment by ibarrond** [comment]
I'm afraid that limitation comes directly from SEAL.

The way I have dealt with it in the past is by reducing the range of the inputs with a manual downscaling (e.g., 1/1000), and compensating it either during the arithmetic circuit (e.g., multiplying by plaintext 1000 after a ctxt-ctxt multiplication, encoding plaintext values with a manual downscale of 1 before a ptxt-ctxt multipliction), or after the circuit evaluation (e.g., upscale the result by 1000 if I performed a ctxt-ctxt multiplication).

**Comment by ibarrond** [comment]
Can you provide some code to try out? I'm afraid I don't have such experience. 

The precision might be worsened by the way we perform scale alignment. A future improvement will be to optionally add a ptxt-ctxt multiplication to rescale more accurately after each multiplication, consuming a bit of extra noise and time but yielding much better results.

**Comment by meirgold** [comment]
Thanks Alberto. 
Currently it's a little difficult for me to provide the code, as it's a part of a larger program and difficult to separate. I will close the issue and reopen once I'm able to provide a better example for this.
The improvement sounds promising and may be useful to me in the future.

Thanks,

Meir


Meir
