### ISSUE TITLE
Will you add self-defined rotation key to Pyfhel?

### ISSUE THREAD

**Issue by EchizenG** [ibarrond/Pyfhel#148]
**Describe the feature**
In SEAL, it is doable to generate rotation key with self-defined steps. This can make one-rotation time consume equals to relineralization. In Pyfhel, I don't find any API to do this. Therefore, I ask here if you will add this feature later. Thank you!

**Is this feature related to a project/objective? Please describe briefly**
The current rotation time consume is HammingDistance(min(k,m/2-k)). Adding the above feature can lead to minimum rotation time consume.

**Comment by ibarrond** [comment]
It can definitely be done! Do you have any SEAL-based code I can use as inspiration? Iw ould probably just modify the `relinKeyGen()` function to allow for optional parameters.

**Comment by EchizenG** [comment]
I modified the example code in SEAL/native/examples/6_rotation.cpp. 

`// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#include "examples.h"
#include <sys/resource.h>
// #include <sys/time.h>
// #include <unistd.h>
// #include <stdio.h>

using namespace std;
using namespace seal;

/*
Both the BFV and BGV schemes (with BatchEncoder) as well as the CKKS scheme support
native vectorized computations on encrypted numbers. In addition to computing slot-wise,
it is possible to rotate the encrypted vectors cyclically.

Simply changing `scheme_type::bfv` to `scheme_type::bgv` will make this example work for
the BGV scheme.
*/
void example_rotation_selfkey_bfv()
{
    // print_example_banner("Example: Rotation / Rotation in BFV");

    EncryptionParameters parms(scheme_type::bfv);

    size_t poly_modulus_degree = 8192;
    parms.set_poly_modulus_degree(poly_modulus_degree);
    parms.set_coeff_modulus(CoeffModulus::BFVDefault(poly_modulus_degree));
    parms.set_plain_modulus(PlainModulus::Batching(poly_modulus_degree, 20));

    SEALContext context(parms);
    // print_parameters(context);
    // cout << endl;

    KeyGenerator keygen(context);
    SecretKey secret_key = keygen.secret_key();
    PublicKey public_key;
    keygen.create_public_key(public_key);
    RelinKeys relin_keys;
    keygen.create_relin_keys(relin_keys);
    Encryptor encryptor(context, public_key);
    Evaluator evaluator(context);
    Decryptor decryptor(context, secret_key);

    BatchEncoder batch_encoder(context);
    size_t slot_count = batch_encoder.slot_count();
    size_t row_size = slot_count / 2;
    // cout << "Plaintext matrix row size: " << row_size << endl;

    vector<uint64_t> pod_matrix(slot_count, 0ULL);
    pod_matrix[0] = 0ULL;
    pod_matrix[1] = 1ULL;
    pod_matrix[2] = 2ULL;
    pod_matrix[3] = 3ULL;
    pod_matrix[row_size] = 4ULL;
    pod_matrix[row_size + 1] = 5ULL;
    pod_matrix[row_size + 2] = 6ULL;
    pod_matrix[row_size + 3] = 7ULL;

    struct timespec start, end;
    // cout << "Input plaintext matrix:" << endl;
    // print_matrix(second_matrix, row_size);

    /*
    First we use BatchEncoder to encode the matrix into a plaintext. We encrypt
    the plaintext as usual.
    */
    Plaintext plain_matrix;
    // print_line(__LINE__);
    // cout << "Encode and encrypt." << endl;
    
    Ciphertext encrypted_matrix;

    GaloisKeys galois_keys;
    std::vector<int> steps;
    for(int i = 1; i <100;i++){
        steps.push_back(i);
    }
    keygen.create_galois_keys(steps, galois_keys);

    Plaintext plain_result;

    for(int i = 1; i < 100; i++)
    {
        clock_gettime( CLOCK_REALTIME, &start );
        // printf("here i am\n");
        evaluator.rotate_rows_inplace(encrypted_matrix, i, galois_keys);
        
        clock_gettime( CLOCK_REALTIME, &end );
        printf("%ld: %f\n", i, (double)(end.tv_nsec-start.tv_nsec)/((double)1000000));
    }

    /*
    Note that rotations do not consume any noise budget. However, this is only
    the case when the special prime is at least as large as the other primes. The
    same holds for relinearization. Microsoft SEAL does not require that the
    special prime is of any particular size, so ensuring this is the case is left
    for the user to do.
    */
}

void example_rotation_selfkey_ckks()
{
    // print_example_banner("Example: Rotation / Rotation in CKKS");

    /*
    Rotations in the CKKS scheme work very similarly to rotations in BFV.
    */
    EncryptionParameters parms(scheme_type::ckks);

    size_t poly_modulus_degree = 8192;
    parms.set_poly_modulus_degree(poly_modulus_degree);
    parms.set_coeff_modulus(CoeffModulus::Create(poly_modulus_degree, { 40, 40, 40, 40, 40 }));

    SEALContext context(parms);
    // print_parameters(context);
    // cout << endl;

    KeyGenerator keygen(context);
    SecretKey secret_key = keygen.secret_key();
    PublicKey public_key;
    keygen.create_public_key(public_key);
    RelinKeys relin_keys;
    keygen.create_relin_keys(relin_keys);
    GaloisKeys galois_keys;
    keygen.create_galois_keys(galois_keys);
    Encryptor encryptor(context, public_key);
    Evaluator evaluator(context);
    Decryptor decryptor(context, secret_key);

    CKKSEncoder ckks_encoder(context);

    size_t slot_count = ckks_encoder.slot_count();
    // cout << "Number of slots: " << slot_count << endl;
    vector<double> input;
    input.reserve(slot_count);
    double curr_point = 0;
    double step_size = 1.0 / (static_cast<double>(slot_count) - 1);
    for (size_t i = 0; i < slot_count; i++, curr_point += step_size)
    {
        input.push_back(curr_point);
    }
    // cout << "Input vector:" << endl;
    // print_vector(input, 3, 7);

    auto scale = pow(2.0, 50);

    // print_line(__LINE__);
    // cout << "Encode and encrypt." << endl;
    Plaintext plain;
    ckks_encoder.encode(input, scale, plain);
    Ciphertext encrypted;
    encryptor.encrypt(plain, encrypted);

    Ciphertext rotated;
    // print_line(__LINE__);
    // cout << "Rotate 2 steps left." << endl;
    struct rusage usage;
    struct timeval start, end;
    getrusage(RUSAGE_SELF, &usage);
    start = usage.ru_stime;
        evaluator.rotate_vector(encrypted, 2, galois_keys, rotated);
    getrusage(RUSAGE_SELF, &usage);
    end = usage.ru_stime;
    printf("CKKS duration: %ld.%lds\n", end.tv_sec-start.tv_sec, end.tv_usec-start.tv_usec);
    // cout << "    + Decrypt and decode ...... Correct." << endl;
    decryptor.decrypt(rotated, plain);
    vector<double> result;
    ckks_encoder.decode(plain, result);
    // print_vector(result, 3, 7);

    /*
    With the CKKS scheme it is also possible to evaluate a complex conjugation on
    a vector of encrypted complex numbers, using Evaluator::complex_conjugate.
    This is in fact a kind of rotation, and requires also Galois keys.
    */
}

void example_rotation_selfKey()
{
    print_example_banner("Example: Rotation");

    /*
    Run all rotation examples.
    */
    example_rotation_selfkey_bfv();
    example_rotation_selfkey_ckks();
}
`
I just create a vector to store steps and feed it to 'keygen.create_galois_keys' and test the rotation time it looks better than default. I have been trying to add this feature but have not done yet.

**Comment by EchizenG** [comment]
Thank you for your work! This looks fantastic. However, I tried to use 'pip install .' in Pyfhel directory but received following error message.

CMake Error: The source directory "/tmp/pip-req-build-ejv9i6hl/Pyfhel/backend/SEAL" does not appear to contain CMakeLists.txt.
  Specify --help for usage, or press the help button on the CMake GUI.
  Error: could not load cache
  building 'Afhel' shared library
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  In file included from /tmp/pip-req-build-ejv9i6hl/Pyfhel/Afhel/Afseal.cpp:32:
  /tmp/pip-req-build-ejv9i6hl/Pyfhel/Afhel/Afseal.h:47:10: fatal error: seal/dynarray.h: No such file or directory
     47 | #include "seal/dynarray.h"
        |          ^~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1

It looks like the compiler cannot find "seal/dynarray.h'.

**Comment by ibarrond** [comment]
@EchizenG could you open a separate `bug_report` issue with all the information required to replicate? It is a very simple issue to solve, but I'd rather document it properly for other people to benefit from the answer. I promise a swift answer!

**Comment by EchizenG** [comment]
Done
The installation issue is here #150
