### ISSUE TITLE
can not find file: `fatal error: seal/dynarray.h: No such file or directory`

### ISSUE THREAD

**Issue by EchizenG** [ibarrond/Pyfhel#150]
**Description**
There was a bug when I was trying to compile and install the package.

error message:

> CMake Error: The source directory "/tmp/pip-req-build-ejv9i6hl/Pyfhel/backend/SEAL" does not appear to contain CMakeLists.txt.
> Specify --help for usage, or press the help button on the CMake GUI.
> Error: could not load cache
> building 'Afhel' shared library
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> In file included from /tmp/pip-req-build-ejv9i6hl/Pyfhel/Afhel/Afseal.cpp:32:
> /tmp/pip-req-build-ejv9i6hl/Pyfhel/Afhel/Afseal.h:47:10: fatal error: seal/dynarray.h: No such file or directory
> 47 | #include "seal/dynarray.h"
> | ^~~~~~~~~~~~~~~~~
> compilation terminated.
> error: command '/usr/bin/gcc' failed with exit code 1

It looks like the compiler cannot find "seal/dynarray.h'.

**Setup:**
 - OS: [e.g. Ubuntu 20.04.5 LTS]
 - Python: 3.8.5
 - C compiler version: GCC 7.3.0
 - Pyfhel Version: 3.3.1

**Comment by ibarrond** [comment]
It seems like there is nothing inside `Pyfhel/backend/SEAL`! To install the library from the Github repository, make sure to download all the submodules with `git clone --recursive [...]`. If you downloaded the repo already, you can instead resort to `git submodule update --init --recursive` to download them.

*TIP: The [`Install & Uninstall`](https://github.com/ibarrond/Pyfhel#install--uninstall) section of the README gives you the instructions to install `Pyfhel`, feel free to suggest changes to the README if you found it unclear!*

**Comment by ibarrond** [comment]
Closing, as it seems the issue should be solved. Feel free to reopen otherwise!
