### ISSUE TITLE
Failed decoding with CKKS: BufferError: scalar buffer is readonly

### ISSUE THREAD

**Issue by SerhatBah** [ibarrond/Pyfhel#151]
**Description**

Hello,
I need your help urgently, and I hope you have time. 
I am currently working on the project (SeCCA).
https://github.com/SerhatBah/SeCCA-CKKS

The work aims to apply the CKKS scheme to the Cheng and Church algorithm through Pyfhel.

Unfortunately, I am currently stuck with an error message I need help solving...

Thank you very much

Error:

/usr/bin/python3.10 /home/serhat/SeCCA-CKKS/SeCCA (CKKS)/secured_cheng_church_yeast.py 
SeCCA Step 2
Number of the Bicluster:1
Traceback (most recent call last):
  File "/home/serhat/SeCCA-CKKS/SeCCA (CKKS)/secured_cheng_church_yeast.py", line 20, in <module>
    biclustering = secca.run(data)
  File "/home/serhat/SeCCA-CKKS/SeCCA (CKKS)/biclustlib/algorithms/type2.py", line 120, in run
    self._multiple_node_deletion(data, rows, cols, msr_thr, HE, t_enc, t_dec)
  File "/home/serhat/SeCCA-CKKS/SeCCA (CKKS)/biclustlib/algorithms/type2.py", line 167, in _multiple_node_deletion
    msr, row_msr, col_msr = self._calculate_msr(data, rows, cols, HE, t_enc, t_dec)
  File "/home/serhat/SeCCA-CKKS/SeCCA (CKKS)/biclustlib/algorithms/type2.py", line 231, in _calculate_msr
    arr_sub_data[i] = HE.encryptFrac(enc_sub_data[i])
  File "Pyfhel/Pyfhel.pyx", line 328, in Pyfhel.Pyfhel.Pyfhel.encryptFrac
  File "<stringsource>", line 675, in View.MemoryView.memoryview_cwrapper
  File "<stringsource>", line 363, in View.MemoryView.memoryview.__cinit__
BufferError: scalar buffer is readonly

Process finished with exit code 1

**Setup:**
 - OS: Ubuntu 22.04.1 LTS
 - Python: 3.10
 - C compiler version: [GCC 11.3.0]
 - Pyfhel Version:  3.3.1

**Comment by ibarrond** [comment]
Hi @SerhatBah. Please fill the bug report appropriately! You just deleted the "**Code To Reproduce Error**" section, but much like in StackOverflow, I expect bug reports to include the code that is faulty in a way that is reproducible. This forces you to prepare a small piece of code that yields that error!

Once you have done so, please change the title of this bug error to something meaningful, and not just the placeholders!

**Comment by SerhatBah** [comment]
Hello @ibarrond ibarrond,
I'm really sorry, I was in such a hurry that I didn't pay attention and also forgot the heading. And thank you for the tips on how to insert everything. I don't have much experience with creating posts and am just learning everything.
I'll try to prepare the code as requested so that you don't have to install everything and I'll send it to you right away.

**Comment by SerhatBah** [comment]
**Code To Reproduce Error**

```
HE = Pyfhel()  # Creating empty Pyfhel object
ckks_params = {
	'scheme': 'CKKS',  # can also be 'ckks'
	'n': 2 ** 14,  # Polynomial modulus degree. For CKKS, n/2 values can be
	#  encoded in a single ciphertext.
	#  Typ. 2^D for D in [10, 16]
	'scale': 2 ** 30,  # All the encodings will use it for float->fixed point
	#  conversion: x_fix = round(x_float * scale)
	#  You can use this as default scale or use a different
	#  scale on each operation (set in HE.encryptFrac)
	'qi_sizes': [60, 30, 30, 30, 60]  # Number of bits of each prime in the chain.
	# Intermediate values should be  close to log2(scale)
	# for each operation, to have small rounding errors.
}

HE.contextGen(**ckks_params)  # Generate context for bfv scheme
HE.keyGen()  # Key Generation: generates a pair of public/secret keys
HE.rotateKeyGen()

data = np.random.randint(0, 5, size=(10, 5))
num_rows, num_cols = data.shape
rows = np.ones(num_rows, dtype=np.bool)
cols = np.ones(num_cols, dtype=np.bool)

 # Encrypting sub_data
        # 1. make sub_data a contiguous array in memory
        # 2. change 2d arrays into 1d
        # 3. Convert plaintext into ciphertext
        # 4. Reshape the array
		
sub_data = data[rows][:, cols]
sub_data = np.ascontiguousarray(sub_data)
enc_sub_data = sub_data.flatten()
arr_sub_data = np.empty(len(enc_sub_data), dtype=PyCtxt)
for i in np.arange(len(enc_sub_data)):
	arr_sub_data[i] = HE.encryptFrac(enc_sub_data[i])
arr_sub_data = arr_sub_data.reshape(sub_data.shape)
```

**produces:**

```
/usr/bin/python3.10 /home/serhat/SeCCA-CKKS/SeCCA (CKKS)/secured_cheng_church_yeast.py
SeCCA Step 2
Number of the Bicluster:1
Traceback (most recent call last):
File "/home/serhat/SeCCA-CKKS/SeCCA (CKKS)/secured_cheng_church_yeast.py", line 20, in
biclustering = secca.run(data)
File "/home/serhat/SeCCA-CKKS/SeCCA (CKKS)/biclustlib/algorithms/type2.py", line 120, in run
self._multiple_node_deletion(data, rows, cols, msr_thr, HE, t_enc, t_dec)
File "/home/serhat/SeCCA-CKKS/SeCCA (CKKS)/biclustlib/algorithms/type2.py", line 167, in _multiple_node_deletion
msr, row_msr, col_msr = self._calculate_msr(data, rows, cols, HE, t_enc, t_dec)
File "/home/serhat/SeCCA-CKKS/SeCCA (CKKS)/biclustlib/algorithms/type2.py", line 231, in _calculate_msr
arr_sub_data[i] = HE.encryptFrac(enc_sub_data[i])
File "Pyfhel/Pyfhel.pyx", line 328, in Pyfhel.Pyfhel.Pyfhel.encryptFrac
File "", line 675, in View.MemoryView.memoryview_cwrapper
File "", line 363, in View.MemoryView.memoryview.cinit
BufferError: scalar buffer is readonly

Process finished with exit code 1
```

**Comment by ibarrond** [comment]
I see the error now! `enc_sub_data[i]` is a single numerical value (of type `int` if I'm not mistaken). Pyfhel V3+ encodes entire 1D vectors into a single ciphertext to benefit from the SIMD techniques of BFV/CKKS schemes. The single-value encoding that your code is using is no longer part of Pyfhel (for being absurdly inefficient). 

To solve the error, encrypt an entire 1D vector using `HE.encryptFrac` instead of a single value (could be column-wise or row-wise).

```python
arr_sub_data = HE.encryptFrac(enc_sub_data.astype(np.float64))
```


Beyond this, I strongly suggest you to take a look at `Demo_3` to understand how to deal with vectorized operations in CKKS.

**Comment by SerhatBah** [comment]
Thank you very much for your help. This information has definitely helped a lot, you are absolutely right. We have changed this place, but still have difficulties. We are doing the encryption in a two dimensional and don't know how to go further by a one dimensional array. 
We get a reshape error after the change. I really would appreciate your help.   


**Code**

```
HE = Pyfhel()  # Creating empty Pyfhel object
ckks_params = {
	'scheme': 'CKKS',  # can also be 'ckks'
	'n': 2 ** 14,  # Polynomial modulus degree. For CKKS, n/2 values can be
	#  encoded in a single ciphertext.
	#  Typ. 2^D for D in [10, 16]
	'scale': 2 ** 30,  # All the encodings will use it for float->fixed point
	#  conversion: x_fix = round(x_float * scale)
	#  You can use this as default scale or use a different
	#  scale on each operation (set in HE.encryptFrac)
	'qi_sizes': [60, 30, 30, 30, 60]  # Number of bits of each prime in the chain.
	# Intermediate values should be  close to log2(scale)
	# for each operation, to have small rounding errors.
}

HE.contextGen(**ckks_params)  # Generate context for bfv scheme
HE.keyGen()  # Key Generation: generates a pair of public/secret keys
HE.rotateKeyGen()

data = np.random.randint(0, 5, size=(10, 5))
num_rows, num_cols = data.shape
rows = np.ones(num_rows, dtype=np.bool)
cols = np.ones(num_cols, dtype=np.bool)

 # Encrypting sub_data
        # 1. make sub_data a contiguous array in memory
        # 2. change 2d arrays into 1d
        # 3. Convert plaintext into ciphertext
        # 4. Reshape the array
		
sub_data = data[rows][:, cols]
sub_data = np.ascontiguousarray(sub_data)
enc_sub_data = sub_data.flatten()
arr_sub_data = np.empty(len(enc_sub_data), dtype=PyCtxt)
for i in np.arange(len(enc_sub_data)):
	arr_sub_data = HE.encryptFrac(enc_sub_data.astype(np.float64))
arr_sub_data = arr_sub_data.reshape(sub_data.shape)
```


**Error**

```
/usr/bin/python3.10 /home/serhat/SeCCA-CKKS/secured_cheng_church_yeast.py 
SeCCA Step 2
Number of the Bicluster:1
Traceback (most recent call last):
  File "/home/serhat/SeCCA-CKKS/secured_cheng_church_yeast.py", line 20, in <module>
    biclustering = secca.run(data)
  File "/home/serhat/SeCCA-CKKS/biclustlib/algorithms/type2.py", line 120, in run
    self._multiple_node_deletion(data, rows, cols, msr_thr, HE, t_enc, t_dec)
  File "/home/serhat/SeCCA-CKKS/biclustlib/algorithms/type2.py", line 167, in _multiple_node_deletion
    msr, row_msr, col_msr = self._calculate_msr(data, rows, cols, HE, t_enc, t_dec)
  File "/home/serhat/SeCCA-CKKS/biclustlib/algorithms/type2.py", line 234, in _calculate_msr
    arr_sub_data = arr_sub_data.reshape(sub_data.shape)
AttributeError: 'Pyfhel.PyCtxt.PyCtxt' object has no attribute 'reshape'

Process finished with exit code 1
```

**Comment by ibarrond** [comment]
At this point you can get rid of the reshape! Oh, please open a new issue if you need further help with `Pyfhel` related errors. Let's keep this issue clean!

If you have doubts on how to implement some math operations efficiently using `Pyfhel` (as it seems to be the case), you can just open an issue with pure `numpy` code performing those operations without encryption, and the request on how to efficiently perform them using HE.

**Comment by lilvmy** [comment]
I meet a same problem, the code is as follow.
def encode_matrix(HE, matrix):
    # Base case: if the matrix is one-dimensional, directly apply encodeFrac to each element.
    if matrix.ndim == 1:
        return np.array([HE.encodeFrac(x) for x in matrix])
    # Recursive case: apply encode_matrix to each sub-array.
    else:
        return np.array([encode_matrix(HE, sub_matrix) for sub_matrix in matrix])
HE = Pyfhel()
ckks_params = {
    "scheme": "CKKS",
    "n": 2**14,
    "scale": 2**40,
    "qi_sizes":[60,40,40,40,60]
}

HE.contextGen(**ckks_params)
HE.keyGen()
HE.rotateKeyGen()
HE.relinKeyGen()
a = np.array([[[1,2,3],[4,5,6]],[[2,3,4],[5,6,7]]])
b=encode_matrix(HE, a)

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 7, in encode_matrix
  File "<input>", line 7, in <listcomp>
  File "<input>", line 7, in encode_matrix
  File "<input>", line 7, in <listcomp>
  File "<input>", line 4, in encode_matrix
  File "<input>", line 4, in <listcomp>
  File "Pyfhel/Pyfhel.pyx", line 742, in Pyfhel.Pyfhel.Pyfhel.encodeFrac
  File "<stringsource>", line 663, in View.MemoryView.memoryview_cwrapper
  File "<stringsource>", line 353, in View.MemoryView.memoryview.__cinit__
BufferError: scalar buffer is readonly
So how do I solve this issue
