### ISSUE TITLE
How to calculate a distance metric between encrypted vectors?

### ISSUE THREAD

**Issue by havik2323** [ibarrond/Pyfhel#155]
Is there a way to calculate a distance metric (euclidean or cosine similarity or manhattan) between two homomorphically encrypted vectors?

I'm attempting to implement a pipeline in which we perform document similarity over a corpus of documents.  We'd like to be able to homomorphically encrypt our document embeddings generated by a transformer model and calculate a distance metric between those vectors (cosine similarity, euclidean, manhattan, or something else) for use as a similarity metric.  We want to do this as the documents in question are sensitive in nature.  It may also be ok to use a HE scheme that supports approximations of certain functions like division as we think this might suffice for our use case.  

Any help or insights would be immensely appreciated!  Thank you so much for the time!

**Comment by ibarrond** [comment]
There is indeed! You just need to rely on a few tricks to overcome the limitations of supported operations in CKKS/BFV schemes (mainly additions and multiplications):

- **Cosine Similarity**: Formulated as `CS(x, y) = (sum(xᵢ * yᵢ))/(||x|| * ||y||)`, it would require a division and a norm.
    - _The trick_: Normalize the vectors `x' = x / ||x||` and `y' = y / ||y||`, encrypt `x'` and `y'` and perform a simple scalar product `sum(xᵢ' * yᵢ')` to obtain the cosine similarity (Check [Demo_7_ScalarProd.py](https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_7_ScalarProd.py) on how to do that).

- **Euclidean Distance**: Formulated as `ED(x, y) = sqrt( sum(xᵢ^2 - yᵢ^2))`, it would require a square root.
    - _The trick_: Settle with the **Squared Euclidean Distance** instead, where `SED = sum(xᵢ^2 - yᵢ^2))`. In Pyfhel you can perform element-wise squaring natively ([Demo_3](https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_3_Float_CKKS.py)), followed by `Pyfhel.cumul_add` for cumulative sum (some examples of this in  [Demo_7](https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_7_ScalarProd.py) and [Demo_8](https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_8_HammingDist.py)).

- **Manhattan Distance**: Formulated as `MD(x, y) = sum(|xᵢ - yᵢ|)`, it would require computing the absolute value.
    - _The trick_: If you encrypt binary values only (that is, `xᵢ , yᵢ ∈ {0,1} ∀ i`), you can reformulate `MD(x, y) = sum((xᵢ - yᵢ)^2) = HD(x, y)`,the Hamming Distance, which is implemented in [Demo_8](https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_8_HammingDist.py). For non-binary vectors you can at least compute the **Squared Manhattan Distance** `SMD(x, y) = sum((xᵢ - yᵢ)^2)`, missing a square root to get the MD.

_General Tip_: Leverage on the operations you can perform before encrypting (e.g., normalization) and after decrypting (e.g., square root of the result) to avoid computing non-linear functions in FHE!

**Comment by havik2323** [comment]
Thank you SO MUCH for the response!!  This is incredible and I'm very appreciative of the help.

**Comment by ibarrond** [comment]
You're welcome! In exchange, please share your code (or at least a link)
here once you write it! It would be a great help for other people with this
same goal in mind

**Comment by ibarrond** [comment]
Closing for the time being!
