### ISSUE TITLE
Executing Example code Test_sum_HElib.cpp leads to an Error

### ISSUE THREAD

**Issue by Foram16** [ibarrond/Pyfhel#16]
Test_sum_HElib.cpp includes a header-file utils/Timer.h which is not available in the repository. Hence the execution "make Test_sum_HElib_x"  leads to an error as stated below.

''''''''''
> electrical@electrical-desktop:~/Downloads/HElib/src$ make Test_sum_HElib_x
> HElib requires NTL version 10.0.0 or higher, see http://shoup.net/ntl
> If you get compilation errors, try to add/remove -std=c++11 in Makefile
> g++ -g -O2 -std=c++11 -pthread -DFHE_THREADS -DFHE_BOOT_THREADS -fmax-errors=2 -o >Test_sum_HElib_x Test_sum_HElib.cpp fhe.a -L/usr/local/lib -lntl -lgmp -lm
> Test_sum_HElib.cpp:2:25: fatal error: utils/Timer.h: No such file or directory
> compilation terminated.
> Makefile:154: recipe for target 'Test_sum_HElib_x' failed
> make: *** [Test_sum_HElib_x] Error 1

''''''''''

**Comment by ibarrond** [comment]
As of today, Pyfhel switched to SEAL as homomorphic encryption library, hence all the previous tests and demos are outdated. Stay tuned for further updates, HElib will be supported again sooner than later.

**Comment by ibarrond** [comment]
I believe i have fixed the error: I added the Timer class inside the `Test_sum_HElib.cpp` class. Closing the issue. Feel free to reopen or open a new one if you find other bugs.
a34c08f91b62638d07ddef20f0f2965e167b5470

**Comment by Foram16** [comment]
Thank you...
