### ISSUE TITLE
CKKS Security Level 

### ISSUE THREAD

**Issue by napoay** [ibarrond/Pyfhel#160]
**CKKS Security Level**

Reference [1] mentioned the security level of CKKS. 

<img width="403" alt="Screen Shot 2022-11-17 at 4 05 57 PM" src="https://user-images.githubusercontent.com/38783332/202390734-6390a253-2950-4790-82dd-0a917a3dd5b4.png">

<img width="432" alt="Screen Shot 2022-11-17 at 4 06 55 PM" src="https://user-images.githubusercontent.com/38783332/202390900-25a476c0-1189-4469-b0ba-70b8e0752a30.png">

In the Pyfhel library, how to choose the correct parameter settings according to the security level?

[1] [https://arxiv.org/pdf/2202.07994.pdf](https://arxiv.org/pdf/2202.07994.pdf)

**Comment by ibarrond** [comment]
Much like for `scheme='BFV'`, `scheme='CKKS'` does admit the `sec` parameter. If not provided, it defaults to 128-bit security, but it can be changed easily:

```python
from Pyfhel import Pyfhel
HE = Pyfhel()
context_params_128 = {"scheme": "ckks", "n": 16384, "scale": 2**40, "qi_sizes": [60]+[40]*7+[60],})
context_gen_result = HE.context(**context_params_128)
print(context_gen_result)
print(HE_128.sec, HE.total_coeff_modulus_bit_count)
#> 'success: valid'
#> 128, 340


context_params_256_invalid = {"scheme": "ckks", "n": 16384, "scale": 2**40, "qi_sizes": [60]+[40]*7+[60], "sec": 256})
context_gen_result = HE.context(**context_params_256_invalid)
print(context_gen_result)
#> 'invalid_parameters_insecure: parameters are not compliant with HomomorphicEncryption.org security standard'

context_params_256_valid = {"scheme": "ckks", "n": 16384, "scale": 2**40, "qi_sizes": [60]+[40]*4+[60], "sec": 256})
context_gen_result = HE.context(**context_params_256_valid)
print(context_gen_result)
print(HE_128.sec, HE.total_coeff_modulus_bit_count)
#> 'success: valid'
#> 256, 220
```

**Comment by napoay** [comment]
Thanks a lot! @ibarrond

**Comment by napoay** [comment]
I have an additional question, does the security level affect the ciphertext size and calculation speed? Intuitively, the higher the security level, the larger the ciphertext, and the slower the calculation speed.

**Comment by ibarrond** [comment]
There are two options:
- You manually select all the parameters, including `n` and `qi` (or `qi_sizes`), and Pyfhel will indicate whether the selected parameters are suitable for the selected security level (yielding 'success: valid' when generating the context with `contextGen`). To work with any set of (potentially insecure) parameters, you can always set `sec=0`. This is the default case for `scheme='ckks'`, where the `qi` selection strongly impacts the capabilities of the system (e.g., the scaling after each multiplication).
- In BFV only, you can leave all the `qi` information empty and Pyfhel will select a set of `qi` according to `n` and `sec`, approaching the max size of `q` as much as possible.

**Comment by ShokofehVS** [comment]
Hi Alberto, would it be possible to help me figure out why we have five elements in the `qi_sizes` as  the number of bits of each prime in the chain. Should it be log base 2 of the security level which is by default is 128? (I'd appreciate if you mention some resources to get to know these parameters as the resource in the [demo](https://pyfhel.readthedocs.io/en/latest/_autoexamples/Demo_3_Float_CKKS.html#sphx-glr-autoexamples-demo-3-float-ckks-py)  is really complicated to understand).

**Comment by ibarrond** [comment]
Besides the first and last modulus in the chain (special primes), in CKKS you need one modulus in the `qi` chain for every mod_switch operation performed. These are typically applied after each multiplication to reduce the scale of the encrypted value. A common strategy to set them is to:
1. Count the multiplication depth required by your algorithm.
2. set as many intermediate primes in the `qi` chain as there are multiplications.
3. Set the bit-size of the intermediate `qi`: the higher you set them the more precision they will hold (and the smaller the rounding errors during rescaling). Typically you want them as big as possible (less than 64bit to fit inside machine words) as long as the total bit-size of the big modulus `q` (product of all `qi`) doesn't exceed the maximum value set by the [HomomorphicEncryption Standard](http://homomorphicencryption.org/wp-content/uploads/2018/11/HomomorphicEncryptionStandardv1.1.pdf) (table 1, and also the table at the beginning of this issue; note that all the distributions yield similar bounds).
