### ISSUE TITLE
How to use Pyfhel in a deep learning task

### ISSUE THREAD

**Issue by helbawy** [ibarrond/Pyfhel#165]
Hello,

I'm working on my bachelor thesis and I'm trying to encrypt the MNIST dataset and then classify using CNN. Is this something possible using pyfhel?

Thank you!

**Comment by ibarrond** [comment]
You can indeed! https://github.com/AlexMV12/PyCrCNN aims to do exactly that, based on Pyfhel.

**Comment by helbawy** [comment]
Thank you I'll check it out
