### ISSUE TITLE
How to understand demo 5 output?

### ISSUE THREAD

**Issue by jnlao** [ibarrond/Pyfhel#166]
Hello, I was going through the Client/Server demo on [https://pyfhel.readthedocs.io/en/latest/_autoexamples/Demo_5_CS_Client.html#sphx-glr-autoexamples-demo-5-cs-client-py](url) and I don't understand the output:

`[Client] Response received! Result is 0.1875, should be 7.7375`

Why is the result different from the expected? I'm fairly new to HE but I understand the basics. Shouldn't the result be the same as expected? I'm an undergrad student and I'm writing a paper on HE for a privacy project and I wanted to go briefly into Pyfhel but I'm having a hard time understanding this output.

<img width="801" alt="Screen Shot 2022-12-08 at 8 34 30 AM" src="https://user-images.githubusercontent.com/63268343/206511025-1e2a8ef4-3b59-4258-89bf-c3eaa67f7e80.png">

**Comment by ibarrond** [comment]
It is a small bug indeed! The division (`/` operator) was encoding the inverse of the value only in the first slot, whereas it is much more natural to encode it in all the slots (as it is already the case with `HE.encode(1/4)`). 7e1cd99 should fix this.

**Comment by ibarrond** [comment]
I just checked the output in the docs for that example, showing:

```
[Client] Response received! Result is 7.7382, should be 7.7375
```

So it is fixed! Closing.

**Comment by jnlao** [comment]
Thank you! I really appreciate it :)
