### ISSUE TITLE
Demo Examples for Version 2

### ISSUE THREAD

**Issue by tanu17** [ibarrond/Pyfhel#17]
Demos and examples have not been updated for version2 for more than 3 months. It will be helpful to provide a document for the functionality and examples on how to use Pyfhel.

**Comment by ibarrond** [comment]
Slowly working on it, for the moment you can profit from the documentation of the API. Demos/examples both in code and inside the docs are soon to follow.
df68a41e79fd17dee31bd798fa63c8410cd170fe

**Comment by ibarrond** [comment]
Demos available (please test!) in https://github.com/ibarrond/Pyfhel/tree/master/examples
Docs available (but still quite limited) in https://ibarrond.github.io/Pyfhel

**Comment by 767472021** [comment]
I wrote a simple Restful Api for this Pyfhel library([](https://github.com/767472021/Pyfhel_Restful_Api)), but it only works on the Linux platform, because the load() function can't work properly on the windows platform,  can you spare time to see it in your busy schedule, thank you.

**Comment by ibarrond** [comment]
Looks promising! I propose you to separate the functions you are performing (you run add, sub and mult for each request, you could instead doan `if/else` to perform just the desired operation). 

I'll make further omments in your repo

**Comment by 767472021** [comment]
yeah，I have tested it many times and used different computers. It is just because the ciphertext exported by the load() function cannot be decrypted on the Windows platform. You can run the following code to have a small test:
```
# -*- coding:utf-8 -*-
from Pyfhel import Pyfhel, PyPtxt, PyCtxt
HE = Pyfhel()
HE.contextGen(p=65537)
HE.keyGen()
integer1 = 10
ctxt = HE.encryptInt(integer1)
ctxt.save("ctxt.c1")
result = ctxt.load("ctxt.c1")
# print(HE.decryptInt(result))
```
![image](https://user-images.githubusercontent.com/19233945/55149050-65fb1f00-5184-11e9-89bf-645ef72fd2a1.png)

![image](https://user-images.githubusercontent.com/19233945/55149101-7f9c6680-5184-11e9-8ba0-aab3dec32237.png)

**Comment by 767472021** [comment]
I print out the load() function to export the "size" attribute of the ciphertext, and find that "size" is equal to 2, which works fine on the Linux platform, so the compatibility problem of the load() function can be solved on the windows10 platform?

**Comment by lorepieri8** [comment]
@ibarrond Is the [README](https://github.com/ibarrond/Pyfhel/tree/master/examples) outdated? Cause the [hello world demo](https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_HelloWorld.py) runs smoothly for me.
Is the demo supposed to be refactored with add, sub, multiply which I see [here](https://ibarrond.github.io/Pyfhel/html/index.html)?

**Comment by ibarrond** [comment]
Demos up to date thanks to commit 7773b1783819b133d85d9de91e7332a4ba1fc309
