### ISSUE TITLE
Can Pyfhel run on GPU？

### ISSUE THREAD

**Issue by napoay** [ibarrond/Pyfhel#171]
**Pyfhel run on GPU**

In cutting-edge research, some homomorphic encryption related works run CKKS in GPU environment.

[PrivFT(Badawi.et.al.2020)](https://arxiv.org/pdf/1908.06972.pdf) provides the first GPU implementation of an RNS variant of the CKKS levelled FHE scheme, but lacks the bootstrapping operation of CKKS.

[Naacl-231(Lee.et.al. 2022)](https://aclanthology.org/2022.naacl-main.231/)  develops an efficient GPU implementation of CKKS which greatly improves computation speed.

so, can Pyfhel run on GPU ?

（ I have tried to run the code provided by Naacl-231, but the code they provide seems to be missing a module.

The setup.py file declares that the hedal.frame module exists, but it does not. ）

**Comment by ibarrond** [comment]
@napoay I wasn't able to access the code from [Naacl-231(Lee.et.al. 2022)](https://aclanthology.org/2022.naacl-main.231/). Would you happen to have access to it?

**Comment by napoay** [comment]
> @napoay I wasn't able to access the code from [Naacl-231(Lee.et.al. 2022)](https://aclanthology.org/2022.naacl-main.231/). Would you happen to have access to it?

The code address provided in the paper is not accessible, but can be found here [https://aclanthology.org/2022.naacl-main.231/](https://aclanthology.org/2022.naacl-main.231/)

But I met a problem:

the setup.py file declares that the hedal.frame module exists, but I can't find the frame package in the hedal directory.

 
![image](https://user-images.githubusercontent.com/38783332/221353787-19fff3c1-fbd4-495e-a010-df6ab8fe7625.png)

**Comment by ibarrond** [comment]
I see. Your best call is probably to ask the authors directly.

**Comment by napoay** [comment]
Asked. They ignore me.
