### ISSUE TITLE
BufferError: scalar buffer is readonly

### ISSUE THREAD

**Issue by allent4n** [ibarrond/Pyfhel#178]
BufferError: scalar buffer is readonly

**Comment by ibarrond** [comment]
Please include all the details to reproduce the error. The "bug template"
should include all the necessary fields. Don't erase any, and fill them all!

**Comment by ibarrond** [comment]
@allent4n This issue is lacking details. Please add them for us to reproduce and diagnose your error. Feel free to reopen this issue or open a new one.
