### ISSUE TITLE
polynomial modulus

### ISSUE THREAD

**Issue by sekar93** [ibarrond/Pyfhel#18]
Is it possible to change the polynomial modulus? It doesn't appear in the arguments of contextGen().

**Comment by ibarrond** [comment]
The parameter `m` in `contextGen()` is coefficient of the polynomial modulus in the form of __1*x^m+1__. I am correcting the documentation right now.

Is this enough? Or would you rather have control over the whole polynomial expression?

**Comment by sekar93** [comment]
That's enough! Thank you!

**Comment by ibarrond** [comment]
Closing issue!
