### ISSUE TITLE
Problem import from Mac M1: 'build/temp.macosx-11.1-arm64-3.10/libAfhel.dylib' (no such file)

### ISSUE THREAD

**Issue by data-science-lover** [ibarrond/Pyfhel#182]
It is indicated on the Pyfhel Pypi page that it is now possible to use Pyfhel on mac since version 3.4.0 (without specifying if we are talking about new mac M1 and M2 or old mac with intel processor).

I tried to install Pyfhel on my Macbook pro M1 but the import of the library seems to be a problem:

from Pyfhel import Pyfhel, PyPtxt, PyCtxt
Traceback (most recent call last):
  File "/Users/lco/opt/anaconda3/envs/my_env/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/lco/opt/anaconda3/envs/my_env/lib/python3.10/site-packages/Pyfhel/__init__.py", line 1, in <module>
    from .Pyfhel import Pyfhel
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: dlopen(/Users/lco/opt/anaconda3/envs/my_env/lib/python3.10/site-packages/Pyfhel/Pyfhel.cpython-310-darwin.so, 0x0002): Library not loaded: build/temp.macosx-11.1-arm64-3.10/libAfhel.dylib
  Referenced from: <94E61721-F935-336D-96D4-7FD17807477A> /Users/lco/opt/anaconda3/envs/my_env/lib/python3.10/site-packages/Pyfhel/Pyfhel.cpython-310-darwin.so
  Reason: tried: 'build/temp.macosx-11.1-arm64-3.10/libAfhel.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSbuild/temp.macosx-11.1-arm64-3.10/libAfhel.dylib' (no such file), 'build/temp.macosx-11.1-arm64-3.10/libAfhel.dylib' (no such file), '/usr/local/lib/libAfhel.dylib' (no such file), '/usr/lib/libAfhel.dylib' (no such file, not in dyld cache).

setup :
numpy==1.24.2
Pyfhel==3.4.1
python==3.10.9
pip ==23.0.1

**Comment by ibarrond** [comment]
Could you run with `-v` (`pip install -v Pyfhel`) to get the full output?

**Comment by ibarrond** [comment]
As luck would have it, I now have a Mac M1. I'll try to install Pyfhel natively in it and report my findings here.

**Comment by ocatak** [comment]
I solved the problem. The missing file was in `/Users/ozgur/miniforge3/lib/python3.9/site-packages/Pyfhel/libAfhel.dylib`. I copied this file into `/usr/local/lib/`. It is working now.

**Comment by ibarrond** [comment]
It is a workaround for the time being, but normally the Pyfhel extensions should detect `libAfhel.dylib` in the local folder and use it. I'll have to check if the setup is missing a `RPATH=.` somewhere.

**Comment by anithag** [comment]
I have the same issue but I could work around it using `export DYLD_LIBRARY_PATH=/opt/homebrew/lib/python3.11/site-packages/Pyfhel`. But now when I am running the examples, I have the following error:

```python3 Demo_1_HelloWorld.py
Traceback (most recent call last):
  File "/Users/anitha_gollamudi/Pyfhel/examples/Demo_1_HelloWorld.py", line 23, in <module>
    from Pyfhel import Pyfhel
  File "/opt/homebrew/lib/python3.11/site-packages/Pyfhel/__init__.py", line 1, in <module>
    from .Pyfhel import Pyfhel
ImportError: dlopen(/opt/homebrew/lib/python3.11/site-packages/Pyfhel/Pyfhel.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '__ZN4seal10Ciphertext12load_membersERKNS_11SEALContextERSiNS_11SEALVersionE'
```

How do I fix this? Should I open a new bug?

**Comment by ibarrond** [comment]
@anithag in short this means that Pyfhel/Python does not find the compiled SEAL library. I suggest you do like @ocatak and copy all the compiled libraries inside `/opt/homebrew/lib/python3.11/site-packages/Pyfhel` to `/usr/local/lib/`, as there might be some static libraries being built that are not automatically recognized.

**Comment by anithag** [comment]
@ibarrond That isn't helping me. I still get the namespace error.

**Comment by ibarrond** [comment]
It took a while, but there is now an official way to install Pyfhel in MacOs using GCC (installed with brew). Take a look at. the README for more info!

**Comment by ibarrond** [comment]
Same as #194 . Closing due to installation in M1 Pro being properly tested and documented in the README.
