### ISSUE TITLE
APIs for matrix operations

### ISSUE THREAD

**Issue by apbhcd** [ibarrond/Pyfhel#183]
**Matrix operations**

APIs for matrix operations

**Are there APIs for Matrix operations**

Pyfhel is a very useful FHE library. Regarding matrix operations such as ciphertext matrix multiplication, plain ciphertext matrix multiplication, etc., can it provide easy-to-use APIs?

**Comment by ibarrond** [comment]
It would be nice indeed!

However, it is tricky to deal with matrices, since BFV/CKKS ciphertexts only hold 1D vectors of a limited size. Would you
- Encrypt matrix rows as ciphertext or matrix columns?
- Split rows/columns evenly across several ciphertext if they are too big or fit as much as possible into a single ciphertext?
- Align columns/rows for vector-matrix multiplication?

In general, I find many of these to be a bit tricky to implement unless you have a fully-fledged compiler receiving your program with your input sizes and data types. This is the approach taken by other libraries (e.g., https://github.com/MarbleHE/HECO/ ). In Pyfhel, I rather leave this for the user to choose.

**Comment by ShokofehVS** [comment]
Awe

> That being said, I generally employ numpy arrays with `object` dtype for 2D data management. Adding an example of this to the documentation would be nice to do!
> 
> Here is an example of this to calculate mean squared residues, where I make common use of list comprehension and encapsulate the result in a `np.array` for ease of use later.
> 
> ```python
> import numpy as np
> from Pyfhel import Pyfhel, PyCtxt
> 
> # HE SETUP
> HE = Pyfhel(
>     context_params={'scheme': 'bfv', 'n': 2 ** 13, 't_bits': 56},
>     key_gen=True
> )
> HE.rotateKeyGen() # Rotation values in the vector
> HE.relinKeyGen()  # Relinearization key generation
> 
> # DATA
> n_rows, n_cols = 2000, 10
> n_elements = n_rows*n_cols
> np.random.seed(42) # Fixed seed for reproducibility
> data = np.random.randint(0, 600, size=(n_rows, n_cols))
> 
> # NON-ENCRYPTED ALGORITHM
> all_msr_sums = np.sum((data * n_elements 
>                     - data.sum(axis=0) * n_cols\
>                     - np.expand_dims(data.sum(axis=1), axis=1) * n_rows 
>                     + data.sum())**2) / (n_elements**3)
> assert np.allclose(all_msr, all_msr_sums) # Check that they yield the same result
> 
> # AUX
> tol = 1e-2
> decr_round = lambda c: np.round(HE.decrypt(c), int(np.log10(1/tol)))
> decr_cols  = lambda c_cols: np.round(
>     np.asarray([HE.decrypt(c) for c in c_cols]), int(np.log10(1/tol))).T
> 
> # ENCRYPTED ALGORITHM
> # encrypt data --> One column per ciphertext
> c_data = np.array([HE.encrypt(data[:,i]) for i in range(n_cols)])
> # sum for each row --> sum all ciphertexts
> c_row_sum = sum(c_data)
> 
> # sum for each column --> sum all elements on each ciphertext
> c_col_sum = np.array([HE.cumul_add(c, in_new_ctxt=True) for c in c_data])
> 
> # sum for all elements --> sum all row/col sums
> c_all_sum = c_col_sum.sum()
> 
> # Square residues (non-normalized)
> sq_res = (c_data * n_elements - c_row_sum * n_cols - c_col_sum * n_rows + c_all_sum)**2
> 
> # CHECKS
> assert np.allclose(data,             decr_cols(c_data)[:n_rows]) #  enc_data
> assert np.allclose(data.sum(axis=1), decr_round(c_row_sum)[:n_rows]) #  row_sum
> assert np.allclose(data.sum(axis=0), decr_cols(c_col_sum)[:n_cols])  #  col_sum
> assert np.allclose(data.sum(),       decr_round(c_all_sum)[:n_cols]) #  all_sum
> ```

Awesome! Didn't you miss somewhere defining all_msr in the sample code?
