### ISSUE TITLE
How to calculate the square root in CKKS?

### ISSUE THREAD

**Issue by Helli3452** [ibarrond/Pyfhel#191]
**Describe the feature**
I am trying to rewrite a calculation that uses the function numpy.sqrt(x) with CKKS. 
Does Pyfhel currently support the functionality of a square root?

**Is this feature related to a project/objective? Please describe briefly**
I am currently working on implementing the Pearson correlation coefficient with CKKS.

**Comment by ShokofehVS** [comment]
Add that, its real application is actually in finding a similarity score of BCCA (https://academic.oup.com/bioinformatics/article/25/21/2795/227776?login=true); another biclustering algorithm :) @ibarrond

**Comment by ibarrond** [comment]
You have two main alternatives:
1. Compute a polynomial approximation of the `sqrt` function, requiring several multiplications to get a good precision. [CryptoDL](https://arxiv.org/abs/1711.05189) can be a good source to find the suitable polynomial approximations.
2. Avoid the square root altogether by modifying your formula. To calculate the Pearson correlation coefficient you could compute the squared Pearson correlation coefficient in the encrypted domain (square the numerator, skip the square root in the denominator), and then perform the square root once you decrypt the result, over the plaintext value.
