### ISSUE TITLE
Managing transparent cyphertext

### ISSUE THREAD

**Issue by CastreseRiccio** [ibarrond/Pyfhel#192]
Hi everyone.
Is there a way to manage a transparent cyphertext?

I try to explain the use case:

Using two omomorphic operations like sum and negate I pickup the value x which is a ciphertex and I'll do

x + (-x)

this operation results in a runtime exception : RuntimeError: result ciphertext is transparent

is there a way to catch this exception?

**Comment by ibarrond** [comment]
@CastreseRiccio if you already know that you are operating `x + (-x)`, why operate at all? You could instead encode a vector of zeros and the result would be identical.

Now, in the event that you had some legitimate reason to do that operation (I'd be curious of it), you can follow #124 to manually disable that exception. If you just want to "catch the exception" in Python, you could do something like:

```python
try:
    #... your code with x +(-x)
except RuntimeError as e:
    if str(e)=='result ciphertext is transparent':
        print('I caught it!')
    else:
        raise e
```

**Comment by CastreseRiccio** [comment]
Thank you both for your answers. @ibarrond i did a little implementation of an homomorphic "equals" that use sum and negate. it works like picking two cyphertexts, make a copy of one, negate it and then sum the two, if the result decrypted will be a vector of zeros it means that the two are equals. It works until i tried to equal the same cyphertext, then it give me the error, which is fine i only wanted to know if you already predicted a way to intercept this error as you show in your answer.
