### ISSUE TITLE
error with installing pyfhel "ERROR: Could not build wheels for Pyfhel"

### ISSUE THREAD

**Issue by aziz07ghm** [ibarrond/Pyfhel#193]
I have two issues @ibarrond
the first, I installed pyfhel 2.0.1, but when I tried to import, I got this error 
ModuleNotFoundError: No module named 'pyfhel'

which leads me to the main issue that made me use pyfhel version 2.0.1 
whenever I try to install the new versions using 
`pip install pyfhel==3.4.0`
or
`pip install pyfhel==3.4.1.`
or even the plain `pip install pyfhel`
I got this error over and over again
![pyfhel issue](https://github.com/ibarrond/Pyfhel/assets/134802240/c23ff4a9-2d1f-46c2-8ca5-324bdbdb08a5)

I need this for my master's thesis. Please help as soon as possible.

**Comment by ibarrond** [comment]
Try with `Pyfhel`, capitalizing the first letter.

For the installation of a more recent version:
- Try in a console with admin rights.
- Otherwise install it in WSL.

**Comment by aziz07ghm** [comment]
Thank you for your replay 
However, I have tried following your instructions, but unfortunately, it didn't work.
I even tried it on kali-linux system VMware version, but it didn't work either, showing the same error message. using sudo the superuser privileges  
![pyfhel issue kali](https://github.com/ibarrond/Pyfhel/assets/134802240/d56d2505-dc7b-42d4-9f3d-a1450c9507c2)

**Comment by ibarrond** [comment]
Closing, since the error was posted as images and not as text.
