### ISSUE TITLE
Inadequate CKKS Parameters for Encrypting a Vector of Dimension 2^17

### ISSUE THREAD

**Issue by Deepthiappasani** [ibarrond/Pyfhel#195]
I am currently using the pyfhel library to encrypt a vector with a dimension of 2^17 (131,072 elements). However, I have encountered difficulties due to the limitations of the CKKS parameters provided in the library. The current parameters, where the polynomial degree (n) scales from 10 to 15, are insufficient to handle such a large vector dimension.

So is there any workaround? Also it would be helpful what all parameters can ckks scheme accept?

**Comment by apbhcd** [comment]
#177

**Comment by Deepthiappasani** [comment]
Thank you.
