### ISSUE TITLE
Multiplying a BGV encrypted integer (array) by a cleartext integer results in an error

### ISSUE THREAD

**Issue by meirgold** [ibarrond/Pyfhel#196]
**Description**
I encrypted an integer and attempted to multiply it by a cleartext integer. This resulted in the following error:
TypeError: <Pyfhel ERROR> multiplicand must be either PyCtxt, PyPtxt or numerical(is <class 'int'> instead)

This works well with the BFV scheme and the error message indicates that numerical values are supported, so I'm not sure why this fails.

**Code To Reproduce Error**
def bgv_mult():
    HE = Pyfhel()
    bgv_params = {
        'scheme': 'BGV',
        'n': 2 ** 13,
        't': 65537,
        'sec': 128,
    }
    HE.contextGen(**bgv_params)  # Generate context for bgv scheme
    HE.keyGen()  # Key Generation: generates a pair of public/secret keys
    HE.rotateKeyGen()  # Rotate key generation --> Allows rotation/shifting
    HE.relinKeyGen()  # Relinearization key generation
    integer1 = np.array([127], dtype=np.int64)
    ctxt1 = HE.encryptBGV(integer1)
    ctxtMul1 = ctxt1 * 2

**Expected behavior**
an encrypted value of [254]

**Setup:**
 - OS: ubuntu
 - Python: 3.10.7
 - C compiler version: GCC 12.2.0
 - Pyfhel Version: 3.4.1

**Comment by AlexanderViand** [comment]
`np.int64`  is not an instance of `int` (nor is `np.array[np.int64]`). You'll need to encode these values into PyPtxt first.
