### ISSUE TITLE
Optimized CKKS parameters settings for only addition operations

### ISSUE THREAD

**Issue by apbhcd** [ibarrond/Pyfhel#198]
How to optimize CKKS parameters to achieve better performance if only addition operation is required?
## Q1: minimum multiplication depth

Deeper multiplication depth sacrifices performance, so I am looking for a limit that is just big enough to enable my computation’s multiplicative depth while sacrificing as little as possible in performance.

Is it possible to reduce the multiplication depth to 0 if I only need to perform addition operations?

Take N=2*13 as an example:

```python3
ckks_params_1 = {'scheme': 'CKKS', 'n': 2**13, 'scale': 2**30,  'qi_sizes': [30, 20, 20, 30]}

ckks_params_2 = {'scheme': 'CKKS', 'n': 2**13, 'scale': 2**30,  'qi_sizes': [30, 20, 30]}

```
Is `ckks_params_2`  better than `ckks_params_1`  for addition?

## Q2:  relationship between scale and qi_sizes

```python3
ckks_params_3 = {'scheme': 'CKKS', 'n': 2**13, 'scale': 2**30,  'qi_sizes': [35, 25, 25, 35]}
```

When I use `ckks_params_3`,  although the key generation valid, the following alert message is returned:
```python3
python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: <Pyfhel Warning> qi_sizes [35, 25, 25, 35] do not support rescaling for scale 1073741824.0.
```
so, what is the relationship between `scale` and `qi_sizes`?

**Comment by ShokofehVS** [comment]
I found a [paper](https://hal.science/hal-04000209v1/file/grote_authorversion_cr.pdf) by Alberto very helpful and informative where in page 6, he explained thoroughly how to set the parameters in CKKS regardless of the main application. You may understand well what the relationship between scale and qi_sizes is.
