### ISSUE TITLE
Unable to set qi sizes for n:2**10 - 2**12: failed to find enough qualifying primes

### ISSUE THREAD

**Issue by Deepthiappasani** [ibarrond/Pyfhel#200]
Description
If I set the qi sizes for n : 2**10 - 2**12. the context is not getting created.

Code To Reproduce Error
///from Pyfhel import Pyfhel
HE = Pyfhel()          
ckks_params = {
    'scheme': 'CKKS',  
    'n': 2^12,        
    'scale': 2^5,     
    'qi_sizes': [15, 5, 5, 5, 15] 
}
HE.contextGen(**ckks_params) 
HE.keyGen()   

**ERROR:**
RuntimeError: failed to find enough qualifying primes
Exception ignored in: 'Pyfhel.Pyfhel.Pyfhel.contextGen'
Traceback (most recent call last):
  File "hello_ckks.py", line 18, in <module>
    HE.contextGen(**ckks_params)  # Generate context for ckks scheme
RuntimeError: failed to find enough qualifying primes
RuntimeError: <Afseal>: Context not initialized
Exception ignored in: 'Pyfhel.Pyfhel.Pyfhel.keyGen'
Traceback (most recent call last):
  File "hello_ckks.py", line 19, in <module>
    HE.keyGen()
RuntimeError: <Afseal>: Context not initialized

Setup:
 - OS:  Ubuntu 20.04.1
 - Python: 3.8.10
 - C compiler version:   9.4.0
 - Pyfhel Version: 3.4.1

**Comment by AlexanderViand** [comment]
The $q_i$ need to be distinct prime numbers that fulfill some very specific conditions and there simply aren't enough of them (if any) with size less than $2^5$. If you were to set the $q_i$ sizes to `[30, 45]`, you should get the same overall modulus size but with enough room for the library to actually find suitable primes of those sizes.

More fundamentally: why do you want to set `'qi_sizes': [15, 5, 5, 5, 15]`?
