### ISSUE TITLE
Doubt regarding multiplication depth

### ISSUE THREAD

**Issue by golfus06** [ibarrond/Pyfhel#202]
As shown in one of the demos that their is a specific noise budget allocated to each cipher text and when multiplied the noise budget decreases and when it reaches to zero the decryption doesn't work correctly. I want to know how this noise budget is calculated and on what parameter the noise budget depends upon can determine for what n and coefficient modulus(q) what will be the noisebudget and under how many operation it will became zero.

**Comment by AlexanderViand-Intel** [comment]
See https://youtu.be/G8idc7koqWs?t=485 for a high-level overview over what noise in FHE is and how it behaves. 

For CKKS specifically, noise is treated a bit differently, and always overlaps with the message (shown nicely in FIgures 1 & 2 of [the original CKKS paper](https://eprint.iacr.org/2016/421.pdf). 

An entity with access to the secret key (and, in the case of CKKS, knowledge of the expected result), can find out the exact noise in a given ciphertext. However, mostly we simply use common heuristics (i.e., limiting the number of multiplications to the number of RNS moduli/level we have available) to manage noise.

There's also theoretical work on estimating noise, but they unfortunately don;'t model real-world FHE well at the moment.

**Comment by AlexanderViand** [comment]
See https://youtu.be/G8idc7koqWs?t=485 for a high-level overview over what noise in FHE is and how it behaves.

For CKKS specifically, noise is treated a bit differently, and always overlaps with the message (shown nicely in Figures 1 & 2 of [the original CKKS paper](https://eprint.iacr.org/2016/421.pdf).

An entity with access to the secret key (and, in the case of CKKS, knowledge of the expected result), can find out the exact noise in a given ciphertext. However, mostly we simply use common heuristics (i.e., limiting the number of multiplications to the number of RNS moduli/level we have available) to manage noise.

There's also theoretical work on estimating noise, but they unfortunately don;'t model real-world FHE well at the moment.

**Comment by golfus06** [comment]
Thanks for the response will surely check the video and documentation
provided, also can I know what all parameters I need to change if i am
selecting different value of "n" in same example, means how we need to set
different parameters, like if i change q or n value the code gives error so
what exactly are the different parameters i can set in the example to see
all different configurations and number of multiplication operations.

**Comment by golfus06** [comment]
ValueError: encryption parameters are not set correctly
Exception ignored in: 'Pyfhel.Pyfhel.Pyfhel.keyGen'
Traceback (most recent call last):
  File "/root/Pyfhel/examples/Demo_6_MultDepth.py", line 97, in <module>
    HE = Pyfhel(key_gen=True, context_params={
ValueError: encryption parameters are not set correctly
RuntimeError: <Afseal>: Context not initialized
Exception ignored in: 'Pyfhel.Pyfhel.Pyfhel.relinKeyGen'
Traceback (most recent call last):
  File "/root/Pyfhel/examples/Demo_6_MultDepth.py", line 107, in <module>
    HE.relinKeyGen()
RuntimeError: <Afseal>: Context not initialized

B1. CKKS context generation
        <ckks Pyfhel obj at 0x7f544d5bfbe0, [pk:-, sk:-, rtk:-, rlk:-, contx(n=16384, t=0, sec=0, qi=[60, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 60], scale=1073741824.0, )]>
Traceback (most recent call last):
  File "/root/Pyfhel/examples/Demo_6_MultDepth.py", line 117, in <module>
    ctxt_x = HE.encryptFrac(arr_x)
  File "Pyfhel/Pyfhel.pyx", line 366, in Pyfhel.Pyfhel.Pyfhel.encryptFrac
  File "Pyfhel/Pyfhel.pyx", line 390, in Pyfhel.Pyfhel.Pyfhel.encryptFrac
RuntimeError: <Afseal>: CKKS context not initialized

i am trying to set different parameter but i wasn't able to can u please give me some guidance that how to set different parameters to check multiplication depths
