### ISSUE TITLE
Can we encrypt multi-dimensional arrays?

### ISSUE THREAD

**Issue by Deepthiappasani** [ibarrond/Pyfhel#204]
like I've 2 arrays:
array1 = [[1.1,2.2],[1.5,2.5]]
array2 = [[5.5,6.6],[4.5,6.7]]

can we encrypt these arrays using CKKS scheme?

**Comment by ibarrond** [comment]
You have to adapt the multi-dimensional arrays to the constraints of FHE
(1D arrays of fixed length), and operate accordingly.

E.g., represent a 2D matrix as m ciphertexts, one per row of up to n
elements, then iterate over each of the ciphertexts and apply the desired
operation (add/multiply) while keeping track of the underlying data sizes.

**Comment by Deepthiappasani** [comment]
Thank you ibarrond for the neat explanation.
As we are  mentioning the qi_sizes in CKKS which is similar to mentioning multiplicative depth of a circuit. Does this mean the CKKS scheme is SHE but not FHE?

**Comment by ibarrond** [comment]
To make it FHE you need bootstrapping. Sadly SEAL does not provide this out
of the box, meaning that we are limited to SHE until we merge the
bootstrapping of OpenFHE.

**Comment by Deepthiappasani** [comment]
Does Pyfhel supports doing the encryption and decryption on GPU to enhance the performance?
