### ISSUE TITLE
libAfhel.so: undefined symbol:

### ISSUE THREAD

**Issue by miglia6** [ibarrond/Pyfhel#206]
Building Pyfhel on Centos7.9 i have got an issue:

python3.9
Python 3.9.16 (main, Jun 27 2023, 15:16:27)
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Pyfhel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/Pyfhel/__init__.py", line 1, in <module>
    from .Pyfhel import Pyfhel
ImportError: /usr/local/lib/python3.9/site-packages/Pyfhel/./libAfhel.so: undefined symbol: _ZNK4seal20EncryptionParameters12save_membersERSo

What is wrong with it ?

**Comment by ibarrond** [comment]
How did you build Pyfhel? And where are you running Python?

**Comment by miglia6** [comment]
Hi,
ok have you reason ... moving from the build directory  and launching python-3.9 >>import Pyfhel" was fine but ..
using : from Pyfhel import Pyfhel the problem appears again:

>>> from Pyfhel import Pyfhel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/python3.9/site-packages/Pyfhel/./libAfhel.so: undefined symbol: _ZNK4seal20EncryptionParameters12save_membersERSo

i have installed  by : git clone   --recursive https://github.com/ibarrond/Pyfhel
But it stops with :
......................
Cloning into 'Pyfhel/backend/palisade'...
error: RPC failed; result=22, HTTP code = 422
fatal: The remote end hung up unexpectedly
Clone of 'https://gitlab.com/palisade/palisade-release' into submodule path 'Pyfhel/backend/palisade' failed

So entering in https://github.com/ibarrond/Pyfhel/tree/master/Pyfhel/backend
i made :  git clone https://gitlab.com/palisade/palisade-development.git
Then build it manually by:
python3.9 setup.py install

Some error happens if i build by pip : pip3.9 install Pyfhel
--------------------------------------
[root@centos79 tmp]# pip3.9 uninstall Pyfhel
Found existing installation: Pyfhel 3.4.1
Uninstalling Pyfhel-3.4.1:
  Would remove:
    /usr/local/lib/python3.9/site-packages/Pyfhel-3.4.1.dist-info/*
    /usr/local/lib/python3.9/site-packages/Pyfhel/PyCtxt.cpython-39-x86_64-linux-gnu.so
    /usr/local/lib/python3.9/site-packages/Pyfhel/PyPoly.cpython-39-x86_64-linux-gnu.so
    /usr/local/lib/python3.9/site-packages/Pyfhel/PyPtxt.cpython-39-x86_64-linux-gnu.so
    /usr/local/lib/python3.9/site-packages/Pyfhel/Pyfhel.cpython-39-x86_64-linux-gnu.so
    /usr/local/lib/python3.9/site-packages/Pyfhel/libAfhel.so
    /usr/local/lib/python3.9/site-packages/Pyfhel/libz.a
    /usr/local/lib/python3.9/site-packages/Pyfhel/libzstd.a
    /usr/local/lib/python3.9/site-packages/Pyfhel/utils/*
Proceed (Y/n)? Y
  Successfully uninstalled Pyfhel-3.4.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@centos79 tmp]# pip3.9 install Pyfhel
Collecting Pyfhel
  Using cached Pyfhel-3.4.1-cp39-cp39-linux_x86_64.whl
Requirement already satisfied: numpy>=1.21 in /usr/local/lib/python3.9/site-packages (from Pyfhel) (1.23.5)
Installing collected packages: Pyfhel
Successfully installed Pyfhel-3.4.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@centos79 tmp]# cd /
[root@centos79 /]# python
python            python2.7         python3.6         python3.9
python2           python3           python3.6m        python3.9-config
[root@centos79 /]# python
python            python2.7         python3.6         python3.9
python2           python3           python3.6m        python3.9-config
[root@centos79 /]# python3.9
Python 3.9.16 (main, Jun 27 2023, 15:16:27)
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Pyfhel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/Pyfhel/__init__.py", line 1, in <module>
    from .Pyfhel import Pyfhel
ImportError: /usr/local/lib/python3.9/site-packages/Pyfhel/./libAfhel.so: undefined symbol: _ZNK4seal20EncryptionParameters12save_membersERSo
>>>
--------------------------------------------------------------------------

Thanks for your help

Andrea

**Comment by miglia6** [comment]
Issue it is  already opened..

**Comment by miglia6** [comment]
This is the sequence , starting from minimal centos 7.9 to reproduce the problem .. what is wrong ?
      yum update
      yum install centos-release-scl
     yum install devtoolset-7-gcc-c++ --enablerepo='centos-sclo-rh'
     scl enable devtoolset-7 'bash'
     yum install epel-release
     yum install python-pip
     sudo yum install gcc openssl-devel bzip2-devel libffi-devel zlib-devel
     wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz
     yum install wget
     wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz
    tar xvf Python-3.9.6.tgz
     cd Python-3.9.6
     ./configure --enable-optimizations
     make
   make altinstall
     pip3.9 install Pyfhel
    git clone --recursive https://github.com/ibarrond/Pyfhel.git
    cd Pyfhel
    pip install .
 
Thank for you help
Andrea

**Comment by miglia6** [comment]
It is related to an issue to retrieve by git your SEAL directory,

**Comment by ibarrond** [comment]
Normally you should see the `SEAL` folder filled with the original repo. If this wasn't the case, it means something went wrong when cloning with `--recursive`. Paying attention to the error messages when cloning should give you the key to solve the issue. Thanks for spotting it out!
