### ISSUE TITLE
how to install pyfhel in macOS

### ISSUE THREAD

**Issue by icedragonK** [ibarrond/Pyfhel#21]
when I install pyfhel, there is an error called:Pyfhel/SEAL/SEAL/seal/locks.h:12:50: error: 'shared_mutex' is unavailable: introduced in macOS 10.12
can you help me to fix it. Thank you.

**Comment by ibarrond** [comment]
I guess by reading the error that you are using Apple. Unfortunately I have never tested Pyfhel in a MAC. Can you Upgrade to macOS 10.12 or later?

**Comment by ibarrond** [comment]
Did you manage to solve it? 'shared_mutex' is a C++ object that is present in rather modern libraries, thus you should get the most recent version possible. Updating the OS  might make it work.

**Comment by icedragonK** [comment]
thanks， I installed pyfhel in my visual machine successfully. 


发自我的 iPhone

**Comment by ibarrond** [comment]
I'm closing this issue, stating that Pyfhel does not support macOS and the only way to install it is by using a Windows/Linux VM.

**Comment by ibarrond** [comment]
Starting witn `v3.4.0` we support MacOS directly! 5c82163d20ba92f1e62035dd655c0c8939e76700

**Comment by data-science-lover** [comment]
> Starting witn `v3.4.0` we support MacOS directly! [5c82163](https://github.com/ibarrond/Pyfhel/commit/5c82163d20ba92f1e62035dd655c0c8939e76700)

Hello Ibarrond,
Do you support Mac M1 version ? or just Mac with Intel ?

**Comment by ibarrond** [comment]
I haven't tested it with M1. If you are committed to it, you can try installing `Pyfhel` on your system, and open a github issue to tackle installation issues.
