### ISSUE TITLE
ImportError: /home/iai/miniconda2/envs/myenv/lib/python3.7/site-packages/Pyfhel/./libAfhel.so: undefined symbol: _ZNK4seal10Ciphertext12save_membersERSo

### ISSUE THREAD

**Issue by mmehedin** [ibarrond/Pyfhel#210]
Hello,

**The installation was complete with:**
```pip install Pyfhel```

Using the import as 
```import Pyfhel```

got the error:
```ImportError: /home/iai/miniconda2/envs/myenv/lib/python3.7/site-packages/Pyfhel/./libAfhel.so: undefined symbol: _ZNK4seal10Ciphertext12save_membersERSo```

Any help is appreciated. Thanks,

**Comment by ibarrond** [comment]
Please fill all the information related to your environment. Otherwise it
is very hard to diagnose.

**Comment by ibarrond** [comment]
Closing, since no additional information was provided.  Might be related to #206
