### ISSUE TITLE
Question about range query operation

### ISSUE THREAD

**Issue by jahidhasanlinix** [ibarrond/Pyfhel#211]
Hi, I have one question about Pyfhel operators, does this library works for a wide range of range query operations or functions and does it work for finding the maximum/larger (>= operators) length or value of it? If yes, any examples or workaround to share to look into to get more understanding of it? Thanks.

**Comment by ShokofehVS** [comment]
As far as I know, FHE schemes like CKKS only support additions and multiplications out of the shelf. Therefore, any non-linear functions (such as [comparison](https://github.com/ibarrond/Pyfhel/issues/154#issuecomment-1314999917)) requires either approximations or circumvention.
