### ISSUE TITLE
How to flip and cumul_add using the cyphertext object

### ISSUE THREAD

**Issue by meirgold** [ibarrond/Pyfhel#213]
Hi,

Following issue #143 @ibarrond added the cumul_add and flip operations which can be called using the HE object,
How can I call these operations using the encrypted object itself (Pyfhel.cyphertext)?
I would have expected something similar to rotate (<< and >>) to be available for use on the cyphertext itself, at least for flip, but I'm not sure where to find it.

Thanks,

Meir

**Comment by ibarrond** [comment]
`cumul_add` of `ctxt` (in a new ciphertext) was already available via: `(+ctxt)`

`flip` of `ctxt`  (in a new ciphertext) is now available upon your request via: `ctxt ^ 1` (it can be called with anything as second operator, the flip operation does not use it).

As per `v3.4.2`, these methods have been included in [`Demo_2_Integer_BFV.py`](https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_2_Integer_BFV.py).

**Comment by ibarrond** [comment]
Closing, as the comment above as well as the Demo_2 answer the question.

**Comment by meirgold** [comment]
Thanks Alberto.
Sorry for the late reply

Meir
