### ISSUE TITLE
How to calculate squared euclidean distance?

### ISSUE THREAD

**Issue by zechuncao** [ibarrond/Pyfhel#218]
Hello, I am in the process of developing a procedure for calculating the squared Euclidean distance using the CKKS scheme. The objective is to determine the distance between the encrypted point's coordinates and the plaintext point's coordinates. To achieve this, I have found the following function:
```python
def l2_dist_sq_ctxt_ptxt(vec_1: PyCtxt, vec_2: PyPtxt, HE: Pyfhel):
    dist_sq = ~(vec_1 - vec_2) ** 2
     dist_sq = ~(vec_1 - vec_2) ** 2
    HE.relinKeyGen()  # relinearize after ctxt-ctxt mults
    dist_sq = HE.cumul_add(dist_sq)
    return dist_sq
```
When I invoke this function only once, the result is accurate. However, when I compute the distance repeatedly, the results become incorrect from the second calculation onward. Upon investigation, I discovered that I need to regenerate the Homomorphic Encryption (HE) object with the original parameters to consistently obtain correct results each time I call this function. While this workaround functions, I suspect I might be making a fundamental error in my approach. I would greatly appreciate any assistance in resolving this issue. Your help is highly valued.

**Comment by zechuncao** [comment]
I also tried to save the HE object to a pickle file, expecting that it would be faster than re-generate it every time. However, loading the binary pickle file fails with missing ckks parameters. I wonder if there is any method we can save the HE object to storage.

**Comment by Shakemilktea** [comment]
Hi, I think you can read [Demo_6_MultDepth.py].(https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_6_MultDepth.py)
Maybe it can solve your problem.

**Comment by zechuncao** [comment]
> Hi, I think you can read [Demo_6_MultDepth.py].(https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_6_MultDepth.py) Maybe it can solve your problem.

Thank you for your reply! I fixed the problem by relinearization after the ciphertext multiplication.

**Comment by ibarrond** [comment]
Related to #132 , the calculation of the Squared Euclidean Distance is actually the same as that of the Hamming distance, except for the fact that inputs are not restricted to {0,1} values. You will find the code to run Hamming in [Demo_8_HammingDist.py](https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_8_HammingDist.py), feel free to use it for SED by just inputting vectors with bigger elements. Oh, and as hinted in the example pointed at by @Shakemilktea, you should always run relinearization after each multiplication!
