### ISSUE TITLE
ValueError: encrypted_ntt and plain_ntt parameter mismatch

### ISSUE THREAD

**Issue by Shakemilktea** [ibarrond/Pyfhel#219]
Hello, I want to design a neural network using Pyfhel for my Master Thesis, but I encountered this issue during the multiplication of plaintext and ciphertext. Through my investigation, I suspect that it might be influenced by the scale_bits size, but I'm not sure why it's having an effect. Did I do something wrong or if there's something I might have missed? Below is the complete error message:

> Traceback (most recent call last):
  File "E:\NCKU\ICLab\code\my_code\Pyfhel\HE_CNN.py", line 171, in <module>
    x = avg_pooling(x)
  File "E:\NCKU\ICLab\code\my_code\Pyfhel\HE_CNN.py", line 65, in avg_pooling
    new_matrix_row_temp.append(np.array(sub_matrix).sum()*0.25)
  File "Pyfhel\\PyCtxt.pyx", line 468, in Pyfhel.PyCtxt.PyCtxt.__mul__
  File "Pyfhel\\Pyfhel.pyx", line 1224, in Pyfhel.Pyfhel.Pyfhel.multiply_plain
ValueError: encrypted_ntt and plain_ntt parameter mismatch

This is the main error code:
```python
def avg_pooling(in_image, size=2, step=2):
    print(in_image)
    new_matrix = []
    for i in range(len(in_image[0]) // step):
        new_matrix_row_temp = []
        for j in range(len(in_image) // step):
            sub_matrix = []
            sub_matrix.append(in_image[step*i][step*j:step*j + size])
            sub_matrix.append(in_image[step*i + size-1][step*j:step*j + size])
            new_matrix_row_temp.append(np.array(sub_matrix).sum()*0.25)
        new_matrix.append(new_matrix_row_temp)
    return new_matrix
``` 

I get wrong by this model:
```python
x = conv2d(ctxt_message)
# x = square(x)
# relinearize_matrix(HE, x)
x = avg_pooling(x)
x = conv2d(x)
x = square(x)
relinearize_matrix(HE, x)
x = avg_pooling(x)  # the place where get the error
```

**Comment by ibarrond** [comment]
Hi @Shakemilktea, the plaintext multiplication of `sub_matrix.sum()` with `0.25` seems to be causing the issue (this is the SEAL [line of code](https://github.com/microsoft/SEAL/blob/main/native/src/seal/evaluator.cpp#L2144) that causes the error). Could you try encoding that `0.25` in a PyPtxt (e.g., `ptxt = HE.encode(0.25)`) and calling `HE..align_mod_n_scale(sub_matrix.sum(), ptxt)`? It looks like you caught a bug!

**Comment by Shakemilktea** [comment]
Hello @ibarrond, thank you for your response! After testing, using HE.align_mod_n_scale(sub_matrix.sum(), ptxt) successfully adjusted the scale_bits of the sub-matrix and the mod_level of ptxt. Unfortunately, the error still exists and seems to not be related to scale_bits. Additionally, if I move the square layer forward, this problem doesn't occur, and only a UserWarning is generated. The results of the decryption are correct in this case. The following are the results of moving the square layer forward:

> Expected answer: [[10932.625]]
E:\NCKU\ICLab\code\my_code\Pyfhel\HE_CNN_CKKS.py:56: UserWarning: Cannot align scales 120 and 30 (available rescalings: [30 60])
  new_matrix_row_temp.append(np.array(sub_matrix).sum()*0.25)
E:\NCKU\ICLab\code\my_code\Pyfhel\HE_CNN_CKKS.py:32: UserWarning: Cannot align scales 150 and 30 (available rescalings: [30 60 90])
  convolution = sub_matrix * kernel
E:\NCKU\ICLab\code\my_code\Pyfhel\HE_CNN_CKKS.py:56: UserWarning: Cannot align scales 180 and 30 (available rescalings: [ 30  60  90 120])
  new_matrix_row_temp.append(np.array(sub_matrix).sum()*0.25)
Encrypt answer [[<Pyfhel Ciphertext at 0x159e301f5b0, scheme=ckks, size=2/2, scale_bits=210, mod_level=5>]]
Decrypt answer: [[array([10932.624508])]]

**Comment by ibarrond** [comment]
Closing as the OP found a fix
