### ISSUE TITLE
HELib Improved Makefile

### ISSUE THREAD

**Issue by Foram16** [ibarrond/Pyfhel#22]
Can this file be used to install HELib.

when i tried to make HELib using this file it resulted in error:

    `libtool: link: g++  -fPIC -DPIC -shared   .libs/NumbTh.o .libs/timing.o .libs/bluestein.o .libs/PAlgebra.o  .libs/CModulus.o .libs/FHEContext.o .libs/IndexSet.o .libs/DoubleCRT.o .libs/FHE.o .libs/KeySwitching.o .libs/Ctxt.o .libs/EncryptedArray.o .libs/replicate.o .libs/hypercube.o .libs/matching.o .libs/powerful.o .libs/BenesNetwork.o .libs/permutations.o .libs/PermNetwork.o .libs/OptimizePermutations.o .libs/eqtesting.o .libs/polyEval.o .libs/extractDigits.o .libs/EvalMap.o .libs/recryption.o .libs/debugging.o .libs/matmul.o .libs/intraSlot.o .libs/binaryArith.o .libs/binaryCompare.o .libs/tableLookup.o   -L/usr/local/lib -lntl /usr/local/lib/libgmp.so -lstdc++ -lm -lc -lgcc_s   -g -O2 -pthread   -pthread -Wl,-soname -Wl,libfhe.so.1 -o .libs/libfhe.so.1.0.0`           
`/usr/bin/ld: /usr/local/lib/libntl.a(FFT.o): relocation R_X86_64_32 against .rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libntl.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:159: recipe for target "libfhe.la" failed
make: *** [libfhe.la] Error 1` 

thank you

**Comment by Foram16** [comment]
ok thank you

**Comment by Foram16** [comment]
I'am trying to wrap HELib code in python using ctypes. I compiled the code using :       `g++ -g -O2 -std=c++11 -pthread -DFHE_THREADS -DFHE_BOOT_THREADS -fmax-errors=2 -fPIC -shared -o pke.so pke.cpp fhe.a -L/usr/local/lib -lntl -lgmp -lm`. 

I'm getting an error:

 ` /usr/bin/ld: fhe.a(NumbTh.o): relocation R_X86_64_32 against ".rodata.str1.8"  can not be used when making a shared object; recompile with -fPIC  fhe.a: error adding symbols: Bad value collect2: error: ld returned 1 exit status`

Sorry, but could you possible tell me what I'm doing wrong. Thank you in advance.

**Comment by ibarrond** [comment]
This question doesn't belong to the issues of Pyfhel, since it is not related to this project. I suggest post it in StackOverflow. 

PS: Unfortunately I have no idea what is wrong. I have no access to your code nor have I touched HElib in about 1 year. Good luck in your search

**Comment by Foram16** [comment]
true... thank you.
