### ISSUE TITLE
How to avoid `scale out of bounds` error in repeated multiplication?

### ISSUE THREAD

**Issue by Dyutighosh** [ibarrond/Pyfhel#221]
I am trying to get an approximation of $1/x$ using the Newton-Raphson based approximation technique of form $y_{i+1} = 2y_i - {y_i}^2x$ with $y_0 = 3e^{x}$. As a result, I need to perform repeated multiplications on the encrypted value. However, after around $10$ multiplications, I am getting $\textit{scale out of bounds}$ error. I am using the following following parameters for the initialization:

`ckks_params = {
    'scheme': 'CKKS',
    'n': 2**15, 
    'scale': 2**60,   
    'qi_sizes': [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60]
}`

Is there any way to perform more multiplications so that I will get a more accurate approximation of $1/x$? I understand it will create more computational overhead but the nature of my problem statement demands a higher degree of precision in the output, even if it comes at the expense of increased computational costs.

**Comment by ShokofehVS** [comment]
I came across an [issue](https://github.com/microsoft/SEAL/issues/182) on SEAL:

“Scale out of bounds error specifically means that the scale of a ciphertext or plaintext is larger than the product of all elements in `coeff_modulus`. If you perform multiplications without rescaling, you can quickly see this error. The more rescaling you perform, the less elements will be left in `coeff_modulus`. Even if you managed to have the same scale in a ciphertext after every multiplication and rescale, eventually the `coeff_modulus` can be too small to accommodate another multiplication.”

That being said, I have created a context for one of my implementations like: 
```
        ckks_params = {
            'scheme': 'CKKS',
            'n': 2 ** 14, #reduce the ciphertext size, hence speeding up the operations
            'scale': 2 ** 30, #based on a good trade-off 
            'qi_sizes': [60] + 10 * [30] + [60] #ensure high precision in encoding and decoding.
        }
```
Of course you can change the parameters according to your application. One good example can be this [issue](https://github.com/ibarrond/Pyfhel/issues/177).

**Comment by Dyutighosh** [comment]
Thank you for your response. But, it seems that I won't be able to carry out repeated multiplications on the encrypted value. Consequently, this limitation will prevent me from using approximation-based methods as well.

**Comment by ShokofehVS** [comment]
I'm not quite sure about my suggestions :)
But I was in doubt whether these resources can be helpful for you to get to know how to deal with your issue:
1.  Multiplication depth in CKKS (https://github.com/ibarrond/Pyfhel/issues/202#issuecomment-1584001286)
2. Approximation for instance in finding the square root
(https://github.com/ibarrond/Pyfhel/issues/191#issuecomment-1538915306)

**Comment by Dyutighosh** [comment]
Thanks a lot, @ShokofehVS for your help. I will look into these resources.

**Comment by ibarrond** [comment]
@Dyutighosh any luck?

**Comment by ibarrond** [comment]
Closing, the above resources should serve to deal with the error.
