### ISSUE TITLE
ERROR: Could not build wheels for Pyfhel, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by mcombinatorics** [ibarrond/Pyfhel#223]
**Description**
Installation with pip install Pyfhel fails with an error. 

**Code To Reproduce Error**
pip install .

**Results in**
In file included from /Users/mojtabaabdolmaleki/Desktop/FHE/Pyfhel/Pyfhel/backend/SEAL/native/src/seal/util/mempool.h:9:
      /Users/mojtabaabdolmaleki/Desktop/FHE/Pyfhel/Pyfhel/backend/SEAL/native/src/seal/util/locks.h:51:18: error: 'shared_mutex' is unavailable: introduced in macOS 10.12
                  std::shared_mutex rw_lock_mutex_{};
                       ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/shared_mutex:181:58: note: 'shared_mutex' has been explicitly marked unavailable here
      class _LIBCPP_TYPE_VIS _LIBCPP_AVAILABILITY_SHARED_MUTEX shared_mutex
                                                               ^
      /Users/mojtabaabdolmaleki/Desktop/FHE/Pyfhel/Pyfhel/Afhel/Afseal.cpp:1067:23: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
          for (int j = 0; j < coeff_modulus_count; j++)
                          ~ ^ ~~~~~~~~~~~~~~~~~~~
      /Users/mojtabaabdolmaleki/Desktop/FHE/Pyfhel/Pyfhel/Afhel/Afseal.cpp:1159:21: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
        for (int j = 0; j < coeff_modulus_count; j++)
                        ~ ^ ~~~~~~~~~~~~~~~~~~~
      2 warnings and 3 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pyfhel
Failed to build Pyfhel
ERROR: Could not build wheels for Pyfhel, which is required to install pyproject.toml-based projects

**Setup:**
 - OS: macOS Ventura
 - Python: [e.g. 3.10.9]
 - C compiler version: [Clang 14.0.6]

**Comment by ZhangLambert** [comment]
I have the same problem! However, I use microsoft.
 note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pyfhel
Failed to build Pyfhel
ERROR: Could not build wheels for Pyfhel, which is required to install pyproject.toml-based projects

**Comment by ibarrond** [comment]
@mcombinatorics try out with GCC instead (take a look at the instructions to install in the readme).

**Comment by ibarrond** [comment]
Closing, as this is solvable with the installation instructions in the repo README.
