### ISSUE TITLE
Installation error of Pyfhel

### ISSUE THREAD

**Issue by ecmikes** [ibarrond/Pyfhel#225]
Subject: Error During Pyfhel Installation on Ubuntu

Dear Ibarrond,

I hope this message finds you well. I am attempting to install Pyfhel on my Ubuntu system (version 20.04.4 LTS) using Python 3.10.4 and encountered an error during the installation process. Here are the details:

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

Python Version: Python 3.10.4

g++ Version: g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

Error Message:
[...]
/tmp/pip-install-crgru3fg/pyfhel_c09d03f5f45b418cbdfa9c5d141fb0f5/Pyfhel/Afhel/Afseal.cpp:167:9: error: declaration shadows a field of 'Afseal' [-Werror,-Wshadow]
  auto &context = *(this->get_context());
        ^
/tmp/pip-install-crgru3fg/pyfhel_c09d03f5f45b418cbdfa9c5d141fb0f5/Pyfhel/Afhel/Afseal.h:241:33: note: previous declaration is here
  shared_ptr<seal::SEALContext> context = NULL;     /**< Context. Used for init*/
                                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 errors generated.
error: command '/usr/bin/clang' failed with exit code 1
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for Pyfhel
Failed to build Pyfhel
ERROR: Could not build wheels for Pyfhel, which is required to install pyproject.toml-based projects

It seems that there is a declaration shadowing issue in the 'Afseal' module. I wanted to bring this to your attention, as it is preventing successful installation on my machine.

Please let me know if there are any specific steps or workarounds to address this issue, or if any updates to Pyfhel are planned that might resolve this problem.

Finally, I tried to install Pyfhel on Win 10 and I have similar errors.
 
Thank you for your time and assistance.

Best regards,
Michael M.

**Comment by ecmikes** [comment]
Dear Friend,

I've successfully installed the Pyfhel library on Windows Subsystem for Linux (WSL)!

Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2022.4

The process went smoothly, and I'm excited about the possibilities this library opens up for secure homomorphic encryption. It's incredible to see how well it integrates with WSL, providing a seamless experience.

Best Regards
Michael M.

**Comment by ibarrond** [comment]
Glad to hear! The error was quite weird, though. I'll patch it just in case, thanks for raising the ticket!
