### ISSUE TITLE
PyFhel installation on ananconda prompt

### ISSUE THREAD

**Issue by Adarshsng** [ibarrond/Pyfhel#23]
i used :- pip install PyFhel , for installing pyfhel on my prompt but  it has been showing errors "  Failed building wheel for Pyfhel", please give a proper procedure to install pyfhel

**Comment by ibarrond** [comment]
Setting this issue as enhancement: Installation with Anaconda. I'll try to discover how to install it.

**Comment by Ichbinhippo** [comment]
anaconda install error is here
http://note.youdao.com/noteshare?id=a294ad38a8102437ce1deee351166dd0&sub=7D812802CF3B41D3AE1CC48FA35E1684

**Comment by fadilazerka** [comment]
Hello, I have the same issue in windows 10, I tried the installation on anaconda environment and non-conda environment. I am getting same error message in both cases. 
Any help will be appreciated!   
Error message: 
 ERROR: Command errored out with exit status 1:
   command: 'c:\devops\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\FADILA~1\\AppData\\Local\\Temp\\pip-install-x19hdnxk\\Pyfhel\\setup.py'"'"'; __file__='"'"'C:\\Users\\FADILA~1\\AppData\\Local\\Temp\\pip-install-x19hdnxk\\Pyfhel\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\FADILA~1\AppData\Local\Temp\pip-wheel-1htpcssf' --python-tag cp36
       cwd: C:\Users\FADILA~1\AppData\Local\Temp\pip-install-x19hdnxk\Pyfhel\
  Complete output (14 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\Pyfhel
  copying Pyfhel\test.py -> build\lib.win-amd64-3.6\Pyfhel
  copying Pyfhel\__init__.py -> build\lib.win-amd64-3.6\Pyfhel
  creating build\lib.win-amd64-3.6\Pyfhel\util
  copying Pyfhel\util\ENCODING_t.py -> build\lib.win-amd64-3.6\Pyfhel\util
  copying Pyfhel\util\__init__.py -> build\lib.win-amd64-3.6\Pyfhel\util
  running build_ext
  building 'Pyfhel.Pyfhel' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for Pyfhel
  Running setup.py clean for Pyfhel
Failed to build Pyfhel
Installing collected packages: Pyfhel
    Running setup.py install for Pyfhel ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\devops\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\FADILA~1\\AppData\\Local\\Temp\\pip-install-x19hdnxk\\Pyfhel\\setup.py'"'"'; __file__='"'"'C:\\Users\\FADILA~1\\AppData\\Local\\Temp\\pip-install-x19hdnxk\\Pyfhel\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\FADILA~1\AppData\Local\Temp\pip-record-ipriav7a\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\FADILA~1\AppData\Local\Temp\pip-install-x19hdnxk\Pyfhel\
    Complete output (14 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\Pyfhel
    copying Pyfhel\test.py -> build\lib.win-amd64-3.6\Pyfhel
    copying Pyfhel\__init__.py -> build\lib.win-amd64-3.6\Pyfhel
    creating build\lib.win-amd64-3.6\Pyfhel\util
    copying Pyfhel\util\ENCODING_t.py -> build\lib.win-amd64-3.6\Pyfhel\util
    copying Pyfhel\util\__init__.py -> build\lib.win-amd64-3.6\Pyfhel\util
    running build_ext
    building 'Pyfhel.Pyfhel' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\devops\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\FADILA~1\\AppData\\Local\\Temp\\pip-install-x19hdnxk\\Pyfhel\\setup.py'"'"'; __file__='"'"'C:\\Users\\FADILA~1\\AppData\\Local\\Temp\\pip-install-x19hdnxk\\Pyfhel\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\FADILA~1\AppData\Local\Temp\pip-record-ipriav7a\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by ZinuoCai** [comment]
I have the same error. Are there any solutions?

**Comment by ZinuoCai** [comment]
> I have the same error. Are there any solutions?

I have solved the problem because I have clang of wrong version.

**Comment by llllllim** [comment]
请问是怎么解决的

**Comment by ibarrond** [comment]
To solve the error, please follow #52 . This is a Windows only error,

**Comment by saja1980** [comment]
I try to install Pyfhel on my machine using the ( pip) command but the installing is stoped with an error "ERROR: Failed building wheel for Pyfhel", what is the problem? can anyone help me to complete my installation, please? Note that, I use windows 10, and python 3.8.5 in PyCharm Community Edition 2020.3.2 x64. The full pip command I used is:

pip install pyfhel

The full error is:

ERROR: Failed building wheel for pyfhel Failed to build pyfhel ERROR: Could not build wheels for pyfhel which use PEP 517 and cannot be installed directly

**Comment by ibarrond** [comment]
Hi @saja1980 , there must be more to your error. Can you run `pip install -v pyfhel` for a verbose output? My guess is that your error is related to a lack of C++14 support. Have you installed any "Microsoft Visual C++ Build Tools"? If not, please do so. The full error may tell you more.

**Comment by saja1980** [comment]
Hi Mr.I installed the visual studio build tools 2019  but the same error appears:
 Building wheel for pyfhel (PEP 517) ... error  ERROR: Command errored out with exit status 1:   command: 'c:\users\dr. saja\appdata\local\programs\python\python38-32\python.exe' 'c:\users\dr. saja\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\DR76E9~1.SAJ\AppData\Local\Temp\tmp70t2xr4p'       cwd: C:\Users\Dr. Saja\AppData\Local\Temp\pip-install-rczoy57v\pyfhel_05731a08288d4130ac108c3870c5607f  Complete output (23 lines):  running bdist_wheel  running build  running build_py  creating build  creating build\lib.win32-3.8  creating build\lib.win32-3.8\Pyfhel  copying Pyfhel\test.py -> build\lib.win32-3.8\Pyfhel  copying Pyfhel\__init__.py -> build\lib.win32-3.8\Pyfhel  creating build\lib.win32-3.8\Pyfhel\util  copying Pyfhel\util\ENCODING_t.py -> build\lib.win32-3.8\Pyfhel\util  copying Pyfhel\util\__init__.py -> build\lib.win32-3.8\Pyfhel\util  running build_clib  building 'Afhel' library  creating build\temp.win32-3.8  creating build\temp.win32-3.8\Pyfhel  creating build\temp.win32-3.8\Pyfhel\Afhel  creating build\temp.win32-3.8\Pyfhel\SEAL  creating build\temp.win32-3.8\Pyfhel\SEAL\SEAL  creating build\temp.win32-3.8\Pyfhel\SEAL\SEAL\seal  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION "-Ic:\users\dr. saja\appdata\local\programs\python\python38-32\include" -IPyfhel -IPyfhel\Afhel -IPyfhel\SEAL\SEAL\seal "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include" /EHsc /TpPyfhel\Afhel\Afseal.cpp /Fobuild\temp.win32-3.8\Pyfhel\Afhel\Afseal.obj -DHAVE_CONFIG_H -O2  Afseal.cpp  Pyfhel\Afhel\Afseal.cpp(33): fatal error C1083: Cannot open include file: 'math.h': No such file or directory  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2  ----------------------------------------  ERROR: Failed building wheel for pyfhelFailed to build pyfhelERROR: Could not build wheels for pyfhel which use PEP 517 and cannot be installed directly

    On Wednesday, April 28, 2021, 12:53:52 AM GMT+3, Alberto Ibarrondo ***@***.***> wrote:  
 
 


Hi @saja1980 , there must be more to your error. Can you run pip install -v pyfhel for a verbose output? My guess is that your error is related to a lack of C++14 support. Have you installed any "Microsoft Visual C++ Build Tools"? If not, please do so. The full error may tell you more.

**Comment by ibarrond** [comment]
Ok,to diagnose your problem i searched for the first appearance of the word ERROR, which is used in:

`fatal error C1083: Cannot open include file: 'math.h': No such file or directory`

Basically, this tells you that the MSVC compiler cannot find `math.h`, which is part of the standard C++ library. In order to solve this (to tell the MSVC where to find the standard library), the simplest way is to include the entire standard library in your System PATH variable. For Windows, this means adding the location of your MSVC to the system PATH variable (`C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC` in my case). If you don't know how to add the VC directory to the Sytem PATH, follow [these instructions](https://www.c-sharpcorner.com/article/add-a-directory-to-path-environment-variable-in-windows-10/). Just in case, reboot after the change to make sure it takes effect.

**Comment by saja1980** [comment]
Same error...
    On Wednesday, April 28, 2021, 12:50:40 PM GMT+3, Alberto Ibarrondo ***@***.***> wrote:  
 
 


Ok,to diagnose your problem i searched for the first appearance of the word ERROR, which is used in:

fatal error C1083: Cannot open include file: 'math.h': No such file or directory

Basically, this tells you that the MSVC compiler cannot find math.h, which is part of the standard C++ library. In order to solve this (to tell the MSVC where to find the standard library), the simplest way is to include the entire standard library in your System PATH variable. For Windows, this means adding the location of your MSVC to the system PATH variable (C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC in my case). If you don't know how to add the VC directory to the Sytem PATH, follow these instructions. Just in case, reboot after the change to make sure it takes effect.

**Comment by ibarrond** [comment]
Can you try compiling a simple HelloWorld in C++ using your MSVC? Add the `math.h` library on the headers, and then compile it (you can use [this guide](https://code.visualstudio.com/docs/cpp/config-msvc) as reference for Visual Studio Code). Again, this error doesn't seem connected to Pyfhel itself, but to your compiler toolchain.

**Comment by ibarrond** [comment]
Just in case, can you open a Powershell, execute `echo $Env:PATH` and share the result?

**Comment by saja1980** [comment]
PS C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools> echo $Env:PATHC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x86;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\devinit;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\;C:\Users\Dr. Saja\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.8;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\MATLAB\R2017a\runtime\win64;C:\Program Files\MATLAB\R2017a\bin;C:\Program Files\Git\cmd;C:\Users\Dr. Saja\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\Dr. Saja\AppData\Local\Programs\Python\Python38-32\;C:\Users\Dr. Saja\AppData\Local\Microsoft\WindowsApps;C:\Users\Dr. Saja\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Dr. Saja\AppData\Roaming\Python\Python38\Scripts;C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.2\bin;;C:\Users\Dr. Saja\AppData\Roaming\Python\Python37\Scripts;C:\Program Files\MySQL\MySQL Server 8.0\bin;C:\Users\Dr. Saja\AppData\Local\GitHubDesktop\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC;;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\NinjaPS C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools>

    On Thursday, April 29, 2021, 12:10:03 PM GMT+3, Alberto Ibarrondo ***@***.***> wrote:  
 
 


Just in case, can you open a Powershell, execute echo $Env:PATH and share the result?

**Comment by ibarrond** [comment]
Ok, your system PATH seems correct. Can you check if the PyCharm configuration also includes the right includes to MSVC? I have always worked with VSCode or Jupyter Notebooks, and I don't know how PyCharm works.

**Comment by saja1980** [comment]
thank you very much ....
    On Sunday, May 2, 2021, 10:09:33 PM GMT+3, Alberto Ibarrondo ***@***.***> wrote:  
 
 


Ok, your system PATH seems correct. Can you check if the PyCharm configuration also includes the right includes to MSVC? I have always worked with VSCode or Jupyter Notebooks, and I don't know how PyCharm works.

**Comment by ibarrond** [comment]
So, did you manage to solve the issue?

**Comment by saja1980** [comment]
unfortanly…  no.. 
There is aproblem in some where that I cannt know it..
Do you thing pycharm caused this?  The library installed in another device which use anacoda with python..!! 
--
Sent from Mail.ru app for Android الأحد, ٢٣ مايو ٢٠٢١, ١١:٥٦ص +03:00 from Alberto Ibarrondo  ***@***.*** :

**Comment by ibarrond** [comment]
It is weird indeed. In the verbose output of `pip -v install Pyfhel` I see that the directory that should include `math.h`, that is, `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include`, is included in your compiler options. Can you check manually if there is a `math.h` in that directory?

**Comment by saja1980** [comment]
Finally, I solve it ..... I formated my c drive and install  all software again .. it installed successfully on the first trythank U very much SirCan I get your private email, please? 

    On Monday, May 24, 2021, 12:58:09 PM GMT+3, Alberto Ibarrondo ***@***.***> wrote:  
 
 


It is weird indeed. In the verbose output of pip -v install Pyfhel I see that the directory that should include math.h, that is, C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include, is included in your compiler options. Can you check manually if there is a math.h in that directory?

**Comment by ibarrond** [comment]
Glad to hear! It must have been something wrong with your MSVC compiler installation. 
PS: My email should be visible in my profile.
