### ISSUE TITLE
How to pickle an Ptxt?

### ISSUE THREAD

**Issue by Shakemilktea** [ibarrond/Pyfhel#234]
Hello, I got some error when pickling ptxt. This is the error:
```
Traceback (most recent call last):
  File "E:\NCKU\ICLab\code\Pyfhel-master\examples\Demo_4_SaveNRestore.py", line 172, in <module>
    pkls_ptxt = pickle.dumps(p)
  File "<stringsource>", line 2, in Pyfhel.PyPtxt.PyPtxt.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```

I'd like to encode the deep learning model's weights, then I can perform operations between the encrypted image and the encoded weights. However, when I attempt to encode the weights, a MemoryError might occur (I guess, because the code will stop without raising an error.) Therefore, I intend to pickle the encoded weights (Ptxt) to avoid overloading the RAM. Pickling ctxt doing well in #81, but pickling ptxt gets error. 

Do you have any advice?

**Comment by ibarrond** [comment]
@Shakemilktea The encoding operation is light-weight compared to the homomorphic operations. That being said, you could:

- Pickle the weights as numpy objects.
- Forl `Pyfhel`, implement the necessary pickling mechanism for `PyPtxt` and merge it on the main repo. This seems quite easy:

   1.  Create a `__reduce__` method in `PyPtxt.pyx` that does exactly [what `PyCtxt.__reduce__` does](https://github.com/ibarrond/Pyfhel/blob/2cd7cc72bd89006ae1adfe6ec6f23b69b9bc4282/Pyfhel/PyCtxt.pyx#L196-L203)
   2. Test it and add some example of its use in an `examples` file.

I'd be happy to provide further assistance if you decide to implement it.

**Comment by Shakemilktea** [comment]
Thanks for your advice! It looks good when multiplying Numpy and Ctxt!
Regarding the pickling of Ptxt, I haven't had experience with Cython before, so I need to study it first.

**Comment by ibarrond** [comment]
Solved then!
