### ISSUE TITLE
Nonetype Error in Demo_HelloWorld.py

### ISSUE THREAD

**Issue by ryandeng1** [ibarrond/Pyfhel#24]
<img width="711" alt="error" src="https://user-images.githubusercontent.com/21270455/52765616-793d9b00-2fd9-11e9-914a-5edcc66187b0.png">

**Comment by ibarrond** [comment]
Looks like your code is not up to date. In commit https://github.com/ibarrond/Pyfhel/commit/560d443b81105f52a196ad16bd54149e90d391d3 the file **PyCtxt.pyx** changed `add_encr` to `add`, solving the issue. 

Please pull the latest version of the repository or reinstall Pyfhel. That should solve your issue.

**Comment by lm-suksomboon** [comment]
I have done git pull as your suggestion, but it still has the same error. Do you have any suggestion? 
<img width="775" alt="Screen Shot 2019-03-14 at 14 12 09" src="https://user-images.githubusercontent.com/46433740/54332886-8777e900-4663-11e9-8f88-41854e93fdba.png">

**Comment by lm-suksomboon** [comment]
Ok! Now I can fix my code. The PyCtxt.py has no problem. However, Demo_HelloWorld.py cannot be complied properly due to wrong add & mult operation commands.
