### ISSUE TITLE
When I run Pyfhel.encodeInt(array), the error is TypeError: a bytes-like object is required, not 'list'

### ISSUE THREAD

**Issue by lilvmy** [ibarrond/Pyfhel#243]
Hello, each professor，
 When I run the code as follows, it displays an error.

HE = Pyfhel()
bfv_params = {
    "scheme": "bfv",
    "n": 2**13,
    "t": 65537,
    "sec": 128
}

HE.contextGen(**bfv_params)
HE.keyGen()
HE.rotateKeyGen()
HE.relinKeyGen()

a = [1,2,3,4]
a1 = HE.enocdeInt(a)
-----------------------------------------------------------------------------------------------------------------------------------------------
  File "Pyfhel/Pyfhel.pyx", line 722, in Pyfhel.Pyfhel.Pyfhel.encodeInt
  File "<stringsource>", line 663, in View.MemoryView.memoryview_cwrapper
  File "<stringsource>", line 353, in View.MemoryView.memoryview.__cinit__
TypeError: a bytes-like object is required, not 'list'

**Comment by ShokofehVS** [comment]
Hello, 
Despite I am not a professor :) but I am very much interested in helping others with their issues and the main author @ibarrond who I believe has even more in-depth knowledge than some professors to share without considerations and help every interested ones among community learn fast and efficiently FHE-related topics on Pyfhel repository. 
All in all, I found [demos](https://pyfhel.readthedocs.io/en/latest/_autoexamples/Demo_2_Integer_BFV.html#sphx-glr-autoexamples-demo-2-integer-bfv-py) including the one for BFV very straightforward to learn this scheme and how to encode/ encrypt array.

**Comment by lilvmy** [comment]
Thank you very much, for this problem I have addressed. But I have met another issue as follows.
I use git clone --recursive https://github.com/ibarrond/Pyfhel.git
cd Pyfhel
modify the pyproject.toml file (SEAL-THROW-xxx=='OFF')
pip install .
the Pyfhel was successfully installed, but when I running my code, it display a error
Traceback (most recent call last):
  File "/home/cysren/home/cysren/Desktop/ld_file/Secure-DNN-Inference-with-Adversarial-training/SimArcMNIST/SimEncryptProcessing.py", line 10, in <module>
    from Pyfhel import Pyfhel
  File "/home/cysren/home/cysren/Desktop/ld_file/Secure-DNN-Inference-with-Adversarial-training/Pyfhel/__init__.py", line 1, in <module>
    from .Pyfhel import Pyfhel
  File "/home/cysren/home/cysren/Desktop/ld_file/Secure-DNN-Inference-with-Adversarial-training/Pyfhel/Pyfhel/__init__.py", line 1, in <module>
    from .Pyfhel import Pyfhel
ModuleNotFoundError: No module named 'Pyfhel.Pyfhel.Pyfhel'

**Comment by ShokofehVS** [comment]
By reading through the previous issues, you might better check your `pip` version (to have the latest); and further on, if possible let's get the Pyfhel again via `pip install Pyfhel` just to see whether this way you can get rid of this issue.

**Comment by ibarrond** [comment]
Please open one github issue per problem. It seems you addressed the original problem, could you share how? If you have any other errors, please file a bug template.
