### ISSUE TITLE
from Pyfhel import Pyfhel, leads error ModuleNotFoundError: No module named 'Pyfhel.Pyfhel.Pyfhel'

### ISSUE THREAD

**Issue by lilvmy** [ibarrond/Pyfhel#244]
When I use git clone source code to install Pyfhel, it is successfully installed.
However, when run from Pyfhel import Pyfhel, it shows that ModuleNotFoundError: No module named 'Pyfhel.Pyfhel.Pyfhel'.
The detail install information as follows.
cd .virtualenvs/ld_env/lib/python3.8/site-package
(ld_env) (base) cysren@cysren-Precision-3660:~/.virtualenvs/ld_env/lib/python3.8/site-packages$ git clone --recursive https://github.com/ibarrond/Pyfhel.git
cd Pyfhel
(ld_env) (base) cysren@cysren-Precision-3660:~/.virtualenvs/ld_env/lib/python3.8/site-packages/Pyfhel$ vim pyproject.toml
![image](https://github.com/ibarrond/Pyfhel/assets/54577185/71684589-46bf-4eca-9dcb-ac11529d9c9e)

(ld_env) (base) cysren@cysren-Precision-3660:~/.virtualenvs/ld_env/lib/python3.8/site-packages/Pyfhel$ pip install .
Processing /home/cysren/.virtualenvs/ld_env/lib/python3.8/site-packages/Pyfhel
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.21 in /home/cysren/.virtualenvs/ld_env/lib/python3.8/site-packages (from Pyfhel==3.4.2) (1.24.4)
Building wheels for collected packages: Pyfhel
  Building wheel for Pyfhel (pyproject.toml) ... done
  Created wheel for Pyfhel: filename=Pyfhel-3.4.2-cp38-cp38-linux_x86_64.whl size=9779869 sha256=080b153b7ac9797139dc05dc8ce36d4bc92a8c261ca1a7a93f53dd3b117268d0
  Stored in directory: /tmp/pip-ephem-wheel-cache-tmovt1j0/wheels/4f/46/f7/5d09c0d2efbdafd30400436d39d2529abcbec5fe324206736d
Successfully built Pyfhel
Installing collected packages: Pyfhel
Successfully installed Pyfhel-3.4.2

However, when I run my code in a folder, it leads an error as follows.
Traceback (most recent call last):
  File "/home/cysren/home/cysren/Desktop/ld_file/Secure-DNN-Inference-with-Adversarial-training/SimpleExample/SimEncryptProcessing.py", line 10, in <module>
    from Pyfhel import Pyfhel
  File "/home/cysren/.virtualenvs/ld_env/lib/python3.8/site-packages/Pyfhel/__init__.py", line 1, in <module>
    from .Pyfhel import Pyfhel
  File "/home/cysren/.virtualenvs/ld_env/lib/python3.8/site-packages/Pyfhel/Pyfhel/__init__.py", line 1, in <module>
    from .Pyfhel import Pyfhel
ModuleNotFoundError: No module named 'Pyfhel.Pyfhel.Pyfhel'

**Comment by ibarrond** [comment]
Again, please fill a complete **bug report**. Take a look at existing github issues.
