### ISSUE TITLE
Pyfhel Upgrade to SEAL v3.2

### ISSUE THREAD

**Issue by ibarrond** [ibarrond/Pyfhel#25]
Not long ago, the original SEAL project was moved to GitHub (https://github.com/microsoft/seal) and several upgrades were included (CKKS scheme). The idea is to upgrade Pyfhel to use this SEAL as a submodule and include all this new functionality.

**Comment by Meirzv** [comment]
Hi @ibarrond,

I wonder if CKKS scheme is already supported? I want to compare performance between BFV and CKKS schemes to an existing application. Thank you!

**Comment by ibarrond** [comment]
I'm afraid not. I already managed to wrap the newest SEAL version with Cython, but there is some work left to be done. Sorry to disappoint

**Comment by AlexanderViand** [comment]
I'll most likely end up having to try and hack together some basic CKKS support for this in the next few days. If you've already got some WIP and/or would be willing to have a quick chat about how to best do this, could you let me know? Thanks in advance!

**Comment by ibarrond** [comment]
Oh sure! I'll contact you by email to chat about it. In short, you can take the master branch of SEAL4Pyfhel (https://github.com/ibarrond/SEAL4Pyfhel/tree/master) and use its Makefile to get the latest SEAL version and prepare it for Pyfhel (details in that repo). After this, you would have to:
- Modify the C++ abstraction of SEAL present in `Pyfhel/Afhel/Afseal.{h, cpp}` using the SEAL examples as reference. All pointer handling should be done at this stage.
- Import the new `Afhel` functions in `Pyfhel/afhel.pxd`, to make them usable by all Cython modules.
- Modify all three `*.pyx` files with these new functions to carry out the desired operations.
- (ideally) Add testing to Afhel (add a new Demo), and Pyfhel (add new tests in `Pyfhel/test.py`)

**Comment by ibarrond** [comment]
Well, closing now that v3 is on its way (`dev` branch). New tests are part of another issue.
