### ISSUE TITLE
Cannot do add, multiply operation (no attribute 'add_encr')

### ISSUE THREAD

**Issue by lm-suksomboon** [ibarrond/Pyfhel#26]
Hi, 
I have a problem with using Pyfhel. I installed with pip install command and tested it with file Demo_Batching_SIMD.py. 

My environment : pip --version pip 19.0.3, Python 3.6.3, numpy==1.16.2, Pyfhel==2.0.0a5, Cython==0.29.6,  g++ --version . g++ (Ubuntu 7.1.0-10ubuntu1~16.04.york0) 7.1.0, gcc (Ubuntu 7.1.0-10ubuntu1~16.04.york0) 7.1.0

The error is shown below. Can you help me?

(FHEenv):~/Pyfhel/examples$ python Demo_Batching_SIMD.py 
==============================================================
===================== Pyfhel HELLO WORLD =====================
==============================================================
1. Creating Context and KeyGen in a Pyfhel Object 
2. Encrypting integers
    int  127 -> ctxt1  <class 'Pyfhel.PyCtxt.PyCtxt'>
    int  -2 -> ctxt2  <class 'Pyfhel.PyCtxt.PyCtxt'>
3. Operating with encrypted integers
Traceback (most recent call last):
  File "Demo_Batching_SIMD.py", line 35, in <module>
    ctxtSum = ctxt1 + ctxt2         # `ctxt1 += ctxt2` for quicker inplace operation
  File "Pyfhel/PyCtxt.pyx", line 126, in Pyfhel.PyCtxt.PyCtxt.__add__
AttributeError: 'NoneType' object has no attribute 'add_encr'
(FHEenv):~/Pyfhel/examples$

**Comment by ibarrond** [comment]
Please have a look at #24.

Looks like your code is not up to date. In commit 560d443 the file PyCtxt.pyx changed add_encr to add, solving the issue.

You should pull the latest version of the repository or reinstall Pyfhel. That should solve your issue.
