### ISSUE TITLE
Test `test_Pyfhel_2d_encode_decode_array` does not work

### ISSUE THREAD

**Issue by marcwil** [ibarrond/Pyfhel#29]
Apparently something with the memory views is not working correctly.
Sometimes this testcase works sometimes it does not work.
When creating and decrypting a ciphertext by hand the same happens when using the `encryptArray` and `decryptArray` functions.

I don't see why this is happening and in doubt I would suggest removing the two functions: encryptBatch and decryptBatch provide basically the same functionality without being weird. We could let encryptBatch support numpy arrays.

**Comment by gaben0** [comment]
@marcwil Not sure if this is related to your issue, but I get strange behavior when using the decryptArray function.
Using this code as a simple example:

```
from Pyfhel import Pyfhel
import numpy as np

HE = Pyfhel()
HE.contextGen(65537, flagBatching=True)
HE.keyGen()

p1 = HE.encodeArray(np.array([1, 2, 3]))
p2 = HE.encodeArray(np.array([4, 5, 6]))
c1 = HE.encrypt(p1)
c2 = HE.encrypt(p2)
c_sum = c1 + c2
c_sub = c1 - c2
p_sum = HE.decryptArray(c_sum)
p_sub = HE.decryptArray(c_sub)
print(np.array(p_sum))
print(np.array(p_sub))
print(np.array(HE.decryptArray(c_sum)))
print(np.array(HE.decryptArray(c_sub)))
```
gives the following output:
```
[-3 -3 -3 ...  0  0  0]
[-3 -3 -3 ...  0  0  0]
[5 7 9 ... 0 0 0]
[-3 -3 -3 ...  0  0  0]
```
It appears the second decryption operation somehow affects the first decrypted array. Using decryptBatch function does not cause this problem. Interestingly, as shown in the last two lines, decrypting as a nested call also produces correct behavior.

**Comment by marcwil** [comment]
Yes I think this is a memory management issue. I hope I'll be able to have a look by the end of this week.

**Comment by ibarrond** [comment]
These methods were using `cython.int64` as data type, which apparently is dependent on the underlying architecture. Hopefully 13aad80 will solve this.

**Comment by ibarrond** [comment]
`p_sum` and `p_sub` happen to be MemoryViews pointing to the same memory:

```bash
>>> p_sum
<MemoryView of 'array' at 0x21d795c68b8>
>>> p_sub
<MemoryView of 'array' at 0x21d795c63a8>
```
One way to solve this is by assigning a numpy array to the result of `HE.decryptArray`:

```python
>>> from Pyfhel import Pyfhel
>>> import numpy as np
>>>
>>> HE = Pyfhel()
>>> HE.contextGen(65537, flagBatching=True)
>>> HE.keyGen()
>>>
>>> p1 = HE.encodeArray(np.array([1, 2, 3], dtype=np.int64))
>>> p2 = HE.encodeArray(np.array([4, 5, 6], dtype=np.int64))
>>> c1 = HE.encrypt(p1)
>>> c2 = HE.encrypt(p2)
>>> c_sum = c1 + c2
>>> c_sub = c1 - c2
>>> p_sum = np.array(HE.decryptArray(c_sum))
>>> p_sub = np.array(HE.decryptArray(c_sub))
>>> print(p_sum)
[5 7 9 ... 0 0 0]
>>> print(p_sub)
[-3 -3 -3 ...  0  0  0]
```
Alternatively we would return the `np.array` directly as the output of the function `decryptArray`. Nonetheless, by wrapping the result around a `np.array`, this issue is solved.
