### ISSUE TITLE
Variable Transfer

### ISSUE THREAD

**Issue by Bandcryption** [ibarrond/Pyfhel#34]
Hello, i'm having trouble with saving some ciphertexts i guess. I have a code, which is like the simple integer summation test, but im trying to use the load and save functions, so with second he(smth like fhe) to do the summation with public key. Then it returns the answer and decrypts in the main he.
But when i try to decrypt, it says "Pyfhel object at xx........" returned a result with an error set.
My code example:

from Pyfhel import Pyfhel,PyCtxt

he = Pyfhel()

he.contextGen(1000)
he.saveContext(b'C:/Users/burhan/Desktop/last/context.txt')
he.keyGen()
he.savepublicKey(b'C:/Users/burhan/Desktop/last/pk.txt')

v1 = 5
v2 = 4
p1 = PyCtxt()
p2 = PyCtxt()
p3 = PyCtxt()
he.encryptInt(v1,p1)
he.encryptInt(v2,p2)

b = he.noiseLevel(p1)
k = he.noiseLevel(p2)
print(p1)
print(p2)
print(b)
print(k)

p1.save(b'C:/Users/burhan/Desktop/last/p1.c1')
p2.save(b'C:/Users/burhan/Desktop/last/p2.c1')

fhe = Pyfhel()
fhe.restoreContext(b'C:/Users/burhan/Desktop/last/context.txt')
fhe.restorepublicKey(b'C:/Users/burhan/Desktop/last/pk.txt')

p6 = PyCtxt()
p4 = PyCtxt()
p5 = PyCtxt()

p4.load(b'C:/Users/burhan/Desktop/last/p1.c1')
p5.load(b'C:/Users/burhan/Desktop/last/p2.c1')

p6 = fhe.add(p4,p5)
p6.save(b'C:/Users/burhan/Desktop/last/p6.c1')
p3.load(b'C:/Users/burhan/Desktop/last/p6.c1')
a = he.decryptInt(p3)
n = he.noiseLevel(p3)

print(a)
print(n) 

I'm assuming its happening because of the windows language coding but im not sure. Thanks for your help , have a nice day!

**Comment by 767472021** [comment]
Yes, we have noticed that when loading and saving ciphertext on Windows platform, this coding problem does exist, and it will take some time to solve. You can also try to modify the "ciphertext. cpp" file and then recompile and install Pyfhel.

**Comment by Bandcryption** [comment]
Hello and thanks for the answer! If i use Ubuntu releases instead of windows, will it be solve my problem?  Lately, im trying to install Pyfhel to a virtual machine which uses Ubuntu release 16.04 to solve the problem.But im new to this platform and i'm receiving errors when i try to install Pyfhel. Thank you again!.

**Comment by 767472021** [comment]
Please elaborate on your mistakes. Better have screenshots?

**Comment by Bandcryption** [comment]
I think im missing a requirement or dependency for Pyfhel. I checked out the numpy and cython and they are installed.Setuptools and versions for numpy and cython are up to date.
![Screenshot from 2019-05-08 08-18-38 (1)](https://user-images.githubusercontent.com/49727576/57440475-c5068600-7250-11e9-8904-9f50a8369900.png)
![Screenshot from 2019-05-08 08-19-21 (1)](https://user-images.githubusercontent.com/49727576/57441267-3dba1200-7252-11e9-9776-1f66babfcf47.png)
![Screenshot from 2019-05-08 08-19-46 (1)](https://user-images.githubusercontent.com/49727576/57441276-43175c80-7252-11e9-8c94-b5a8ea429e4a.png)
I'm assuming having those errors because of the gcc, i thought i installed the gcc before. Now working on that. Since im new to linux, sorry for the trouble. Thanks a lot for your help!

**Comment by 767472021** [comment]
1.git clone https://github.com/ibarrond/Pyfhel.git
2.cd Pyfhel
3.pip install .

**Comment by Bandcryption** [comment]
Hello and thanks for all the answers. I solved the problem and installed Pyfhel. My gcc was outdated,that caused the problem. Thanks a lot!
