### ISSUE TITLE
Errors after installation of Pyfhel

### ISSUE THREAD

**Issue by maheshidrbt** [ibarrond/Pyfhel#36]

**Comment by maheshidrbt** [comment]
I successfully installed the Pyfhel. When i am trying to execute the demo programs which are their in examples folder i am getting errors "no module named Pyfhel".  I tried the other way of installing (using ./configure), it also gave me the errors. The screenshots are attached with this mail. 
![successful pyfhel installation](https://user-images.githubusercontent.com/49904269/56661041-843e3700-66be-11e9-8028-17c16e18e4de.png)
![ERROR WITH configure](https://user-images.githubusercontent.com/49904269/56661061-90c28f80-66be-11e9-8a12-5af58cfb2dfd.png)
![errors while executing programs](https://user-images.githubusercontent.com/49904269/56661062-90c28f80-66be-11e9-8476-c1d4b6e8d339.png)
Kindly tell me   
                                 1) How to run Demo programs which are their in the examples
                                 2) How to use the SEAL latest library through Pyfhel??

**Comment by marcwil** [comment]
Hi,

1) the Demo programs are not up to date at the moment.
    However, everything described in this [blog post](https://marcwil.github.io/jekyll/update/2019/03/15/intro-homomorphic-encryption.html)
    should work.
2) I am planning to work on SEAL 3 integration, but as this is just a hobby project please expect this to take weeks.

**Comment by ibarrond** [comment]
Installation, numpy issues and demos solved in recent versions of the library.
