### ISSUE TITLE
Test Examples-Demo_float for Version 2

### ISSUE THREAD

**Issue by voidxb** [ibarrond/Pyfhel#37]
Error:
>>> ctxtSum = ctxt1 + ctxt2         # `ctxt1 += ctxt2` for quicker inplace operation
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Pyfhel/PyCtxt.pyx", line 126, in Pyfhel.PyCtxt.PyCtxt.__add__
AttributeError: 'NoneType' object has no attribute 'add_encr'

**Comment by voidxb** [comment]
Why NoneType?

**Comment by 767472021** [comment]
Are you installing the latest version 2.0.1?

**Comment by ibarrond** [comment]
Sounds similar to #26 . Closing due to repetition
