### ISSUE TITLE
Division support

### ISSUE THREAD

**Issue by Fiono11** [ibarrond/Pyfhel#38]
Does this library support division? Thank you.

**Comment by 767472021** [comment]
So far, only add、subtract、multiplication can be supported.

**Comment by marcwil** [comment]
No just as in SEAL itself this is not supported.

**Comment by ibarrond** [comment]
Nonetheless, you can circumvent this for certain cases if you invert the float value before encrypting and then multiplying instead of dividing.

**Comment by ibarrond** [comment]
Some minor division support was added in v2.2.1. For FRACTIONAL encoding you can now divide a ciphertext by a plaintext value.
