### ISSUE TITLE
duplicate examples

### ISSUE THREAD

**Issue by bcebere** [ibarrond/Pyfhel#39]
The following examples share the exact same code, and some of them do not reflect their name. It would be nice to be synced.

https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_HelloWorld.py

https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_Batching_SIMD.py

https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_ContextParameters.py

https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_Float.py

**Comment by ibarrond** [comment]
Solved! Now we have up to date demos in 7773b1783819b133d85d9de91e7332a4ba1fc309
