### ISSUE TITLE
Conflicting Encoding types

### ISSUE THREAD

**Issue by lorepieri8** [ibarrond/Pyfhel#42]
In multiple places I see Conflicting Encoding types in the comments, for instance in
 https://github.com/ibarrond/Pyfhel/blob/master/Pyfhel/PyCtxt.pyx

you can find both

`# Encoding types: 1-UNDEFINED, 2-INTEGER, 3-FRACTIONAL, 4-BATCH`

and 

`"""Sets Encoding type: 0-UNDEFINED, 1-INTEGER, 2-FRACTIONAL, 3-BATCH""" `

**Comment by ibarrond** [comment]
Corrected in 10afb62. Default encodings are the ones below:

    0-UNDEFINED, 1-INTEGER, 2-FRACTIONAL, 3-BATCH
