### ISSUE TITLE
incorrect result when multiplying 3 numbers

### ISSUE THREAD

**Issue by kcsmta** [ibarrond/Pyfhel#44]
I installed pyfhel and ran some code. The operations performed on 2 numbers worked well but with the 3rd number, the result was wrong. This is my code:

```
from Pyfhel import Pyfhel
HE = Pyfhel()
HE.contextGen(p=65537)
HE.keyGen()

a = 1.1
b = 2.2
c = 3.0

enc_a = HE.encryptFrac(a)
enc_b = HE.encryptFrac(b)
enc_c = HE.encryptFrac(c)

print(HE.decryptFrac(enc_a*enc_b))
print(HE.decryptFrac(enc_b*enc_c))
print(HE.decryptFrac(enc_a*enc_b*enc_c))
```
the results are:

```
2.4199999982956797
6.599999999860302 
2.925756250316916e+18
```

**Comment by marcwil** [comment]
This is very likely to be an issue with noise (which is inherent to the type of cryptography used in the underlying SEAL library).
You can use `HE.noiseLevel(ciphertext)` to determine the remaining noise budget (requires access to private key). If it reaches 0, then the ciphertext polynomial is indistinguishable from random noise and can no longer be decrypted.

If you use suitable parameters for `contextGen` you can increase the noise budget, trading it for worse performance. See also my [blog post](https://marcwil.github.io/jekyll/update/2019/03/15/intro-homomorphic-encryption.html).

**Comment by kcsmta** [comment]
> This is very likely to be an issue with noise (which is inherent to the type of cryptography used in the underlying SEAL library).
> You can use `HE.noiseLevel(ciphertext)` to determine the remaining noise budget (requires access to private key). If it reaches 0, then the ciphertext polynomial is indistinguishable from random noise and can no longer be decrypted.
> 
> If you use suitable parameters for `contextGen` you can increase the noise budget, trading it for worse performance. See also my [blog post](https://marcwil.github.io/jekyll/update/2019/03/15/intro-homomorphic-encryption.html).

Thank you for your answer. Operators can work when I increase _m_ and decrease _p_ parameters.
