### ISSUE TITLE
Multiplication

### ISSUE THREAD

**Issue by Airien1992** [ibarrond/Pyfhel#45]
There is an issue with the multiplication part of two ciphertexts. The issue is present for integers and fractions (tested).
![изображение](https://user-images.githubusercontent.com/11157464/81384367-d60eff00-9111-11ea-82a0-81004b4e55ea.png)
![изображение](https://user-images.githubusercontent.com/11157464/81384379-e030fd80-9111-11ea-9f7c-088c62564c1c.png)
![изображение](https://user-images.githubusercontent.com/11157464/81384402-e9ba6580-9111-11ea-8135-6b11dda2963c.png)
Also in the demo's the error pops up.
Is it an overflow?

**Comment by marcwil** [comment]
see #44
