### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by giraffeCjl** [ibarrond/Pyfhel#46]
When I execute the following command
 > ./configure	
   >cmake .
   > make
   > make install
These are all working fine.
But, an error is still reported when running examples: ImportError: No module named 'Pyfhel'
My system configuration is:Ubuntu16.04  Python 3.5 & Cython on top of C++17 g++==7.5.0

**Comment by marcwil** [comment]
Have you tried simply doing `pip install Pyfhel`?

**Comment by giraffeCjl** [comment]
> Have you tried simply doing `pip install Pyfhel`?

This command did not work for me.

**Comment by ibarrond** [comment]
The Makefile installation is now discouraged. Please use the standard installation with `pip install Pyfhel` or `git clone --recursive https://github.com/ibarrond/Pyfhel.git` followed by `pip install .`; commit 5f25a54fec9e064d4fe314f0b7444c482e361c5a should have solved the installation issues.
