### ISSUE TITLE
"pip install pyfhel" goes tits up without numpy dep

### ISSUE THREAD

**Issue by aspenforest** [ibarrond/Pyfhel#48]
Pyfhel does not automatically detect numpy as a dependency and install it.
Rather, it throws a traceback error "numpy not found" (in PyCharm).

Edit: after I manually installed numpy, the pyfhel install command executed fine.

Env: Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)] on win32

**Comment by ibarrond** [comment]
Weird! We have it defined in [`requirements.txt`](https://github.com/ibarrond/Pyfhel/blob/master/requirements.txt) and it is invoked in the [`setup.py`](https://github.com/ibarrond/Pyfhel/blob/master/setup.py#L118)

**Comment by aspenforest** [comment]
Okay, I found out the problem, and it has multiple facets. 
You have defined a requirements.txt file, but you do not parse it, and you define the setup function with 'setup_requires' at the bottom of the file, meaning that 'import numpy' gets parsed first, as it's at the top of the file, before the setup function has had the chance to execute, as all scripts are parsed from top to bottom.

**Comment by aspenforest** [comment]
You could choose a solution from here: [Install dependencies from setup.py](https://stackoverflow.com/questions/26900328/install-dependencies-from-setup-py)

**Comment by aspenforest** [comment]
In the setup.py file, the dependencies need to be resolved at the top of the file, before any of those deps can be imported.

**Comment by ibarrond** [comment]
Oooh, I understand the issue: we need to know the numpy installation folder to extract headers in order to `CYTHONIZE` the packages, but we only define the installation at the end. Is there a way to install `numpy` without setting up the package? Otherwise we might have to run always `pip install -r requirements.txt` before anything else, which could mess up with PyPi.

**Comment by aspenforest** [comment]
To be honest, I have not tested any of the solutions, so I don't know if they work, but based on my understanding on how Python scripts are parsed, either of them should work fine as long as the deps are resolved before the parser encounters any dependent import statements.

**Comment by ibarrond** [comment]
4bbc5106a Should do the trick.
