### ISSUE TITLE
Runtime error with classification models on data encrypted with Pyfhel

### ISSUE THREAD

**Issue by iamsoze** [ibarrond/Pyfhel#50]
Hi,

I recently got my hands-on with this amazing library. I was able to encrypt/decrypt a simple image with help of Pyfhel's encrypt/decrypt operations. The image was converted to a 1D array first and then encryptBatch was applied. The resulted PyCtxt was decrypted with decryptBatch and converted back to image matrix while preserving its shape to get the original image.

I need to apply a _classification model on this encrypted data_ now. The model should train with encrypted data and an unencrypted or encrypted label and predict the output.

However, I am getting following runtime error while training the model.

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)
<ipython-input-209-cbbcbc2eaff2> in <module>
----> 1 clf = LogisticRegression(random_state=42,verbose=10).fit(X_train, y_train)

~/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py in fit(self, X, y, sample_weight)
   1525 
   1526         X, y = check_X_y(X, y, accept_sparse='csr', dtype=_dtype, order="C",
-> 1527                          accept_large_sparse=solver != 'liblinear')
   1528         check_classification_targets(y)
   1529         self.classes_ = np.unique(y)

~/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py in check_X_y(X, y, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, multi_output, ensure_min_samples, ensure_min_features, y_numeric, warn_on_dtype, estimator)
    753                     ensure_min_features=ensure_min_features,
    754                     warn_on_dtype=warn_on_dtype,
--> 755                     estimator=estimator)
    756     if multi_output:
    757         y = check_array(y, 'csr', force_all_finite=True, ensure_2d=False,

~/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
    529                     array = array.astype(dtype, casting="unsafe", copy=False)
    530                 else:
--> 531                     array = np.asarray(array, order=order, dtype=dtype)
    532             except ComplexWarning:
    533                 raise ValueError("Complex data not supported

~/anaconda3/lib/python3.7/site-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
     83 
     84     """
---> 85     return array(a, dtype, copy=False, order=order)
     86 
     87

~/anaconda3/lib/python3.7/site-packages/pandas/core/series.py in __array__(self, dtype)
    752               dtype='datetime64[ns]')
    753         """
--> 754         return np.asarray(self.array, dtype)
    755 
    756     # ----------------------------------------------------------------------

~/anaconda3/lib/python3.7/site-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
     83 
     84     """
---> 85     return array(a, dtype, copy=False, order=order)
     86 
     87

~/anaconda3/lib/python3.7/site-packages/pandas/core/arrays/numpy_.py in __array__(self, dtype)
    182 
    183     def __array__(self, dtype=None) -> np.ndarray:
--> 184         return np.asarray(self._ndarray, dtype=dtype)
    185 
    186     _HANDLED_TYPES = (np.ndarray, numbers.Number)

~/anaconda3/lib/python3.7/site-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
     83 
     84     """
---> 85     return array(a, dtype, copy=False, order=order)
     86 
     87

Pyfhel/PyCtxt.pyx in Pyfhel.PyCtxt.PyCtxt.__float__()
RuntimeError: <Pyfhel ERROR> wrong PyCtxt encoding (not FRACTIONAL)

**Comment by ibarrond** [comment]
Can you share your code further? I'm afraid it is quite hard to replicate and investigate otherwise.

**Comment by ibarrond** [comment]
Maybe related to #42? If so, it was hopefully solved. Please try again with the latest version of Pyfhel. If the error persists, please provide code to reproduce the error.
