### ISSUE TITLE
How do I implement SIMD operations？

### ISSUE THREAD

**Issue by zhhhhhh** [ibarrond/Pyfhel#55]
Dear developer, I downloaded this file earlier and found the Demo_Batching_SIMD.py file in examples does not mention SIMD operation, Could you show me an example of SIMD operation? Thanks.

**Comment by ibarrond** [comment]
Here is the example you requested! Updated in 4a651b9:
https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_SIMD.py
