### ISSUE TITLE
Make Afhel

### ISSUE THREAD

**Issue by joselcaguilar** [ibarrond/Pyfhel#6]
Hi Alberto,

I'm starting my final project master's degree and your python project is a must :)

I'm trying to make install everything (Ubuntu 16.04.2) and the first stopper is when I have tried to make & make install Afhel, HELib has been installed like a charm, however it throws an error:
`Afhel.cpp:50:14: error: definition of implicitly-declared ‘Afhel::Afhel()’
 Afhel::Afhel(){}
              ^
compilation terminated due to -Wfatal-errors.
Makefile:145: recipe for target 'Afhel.lo' failed
make: *** [Afhel.lo] Error 1`

Could I have some advices to fix that and work with this Python project?
If you want to speak in Spanish about this, you can reach me at LinkedIn (request has been sent from myself).

Thanks in advance!

P.S.- Also, I have modified some separator errors in the makefiles due to spaces vs tab.
P.S.2.- Could you update the tutorial to install it with the new version? +The new SEAL library should be get from: https://download.microsoft.com/download/B/3/7/B3720F6B-4F4A-4B54-9C6C-751EF194CBE7/SEAL_2.3.1.tar.gz

The version 2.3.0 is not available anymore :(

**Comment by ibarrond** [comment]
Hi! Unfortunately right now I am in process of developing a more stable version, but it is taking longer than expected. As of today, I cannot guarantee it will work the way it should. I will still require around 2-3 weeks to make Pyfhel work properly. For the moment, as you may have noticed, I am going to be covering SEAL firstly.

I am sorry about the mistakes in the Makefiles! I corrected them in version 2, but probably forgot to do so in master branch.

Finally, regarding SEAL 2.3.1, I noticed the update 2 days ago, and I'm still working my way around it.

Apologies for a disappointing answer, but that is all I can offer as of today.

**Comment by ibarrond** [comment]
The bug should be fixed now! I pushed a fix to the original version, and version 2 should be working allright!
