### ISSUE TITLE
Shift operations among encrypted values

### ISSUE THREAD

**Issue by comidan** [ibarrond/Pyfhel#60]
Hello!

I just wanted to ask whether the shift operator was going to be implemented maybe in the future, since I saw in the old documentation the shift function reported in the class Pyfhel: "shift -> SHIFT each cyphertext inside PyCtxt ctxt for each ID in it."

Thank you!

By the way, amazing work with this library. I'm doing some research in this field and I found using Pyfhel really straightforward.

**Comment by ibarrond** [comment]
Thanks for the pointers! I just pushed v2.2.2 showcasing the already existing shift/rotation functionality for BATCH encoding. Have a look at the [`Demo_SIMD.py`](https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_SIMD.py#L81).

**Comment by comidan** [comment]
> Thanks for the pointers! I just pushed v2.2.2 showcasing the already existing shift/rotation functionality for BATCH encoding. Have a look at it on line 81 of [`Demo_SIMD.py`](https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_SIMD.py#L81).

Thank you!

**Comment by comidan** [comment]
Hello @ibarrond , I'm sorry to bother you again. I was continuing my work using your library and I think there might be something wrong in the last Pyfhel version.

When I initially opened this issue there was an older version of Pyfhel which allowed me to perform shift operation using as the amount of bits to shift an encrypted or encoded value.

While now, in the 2.3.1 version, if I try to run the same exact code I will get an error saying:

```
---> ctxt1_rot = ctxt1 << intctxt2

Pyfhel/PyCtxt.pyx in Pyfhel.PyCtxt.PyCtxt.__lshift__()

Pyfhel/Pyfhel.pyx in Pyfhel.Pyfhel.Pyfhel.rotate()

TypeError: an integer is required
```

And I think it's strange, given that in a previous Pyfhel version it worked very well.

If you want to take a better look at what I'm talking about I uploaded here on Colab the same notebook while using first Pyfhel 2.2.4 and then 2.3.1, showing that differently from the last version in a previous one it worked very well.
The rotation operator usage is in the last cell of both notebooks.

2.2.4 version: https://colab.research.google.com/drive/1_mVbTtCGLzi7k0EcpqnSJ5Y_pEpk6Ui5?usp=sharing
2.3.1 version: https://colab.research.google.com/drive/1Ec93uw1XXRKNmzDbHBLzbgIXxlXJ4VKN?usp=sharing

**Comment by ibarrond** [comment]
Closing as the issue was answered
