### ISSUE TITLE
Encrypt a pandas Dataframe

### ISSUE THREAD

**Issue by ivanv6** [ibarrond/Pyfhel#62]
Hi, thanks for your work. It is very interesting and promising. One question: are you considering to encrypt also pandas dataframe? Or there is a method already implemented? Thanks!

**Comment by ibarrond** [comment]
Hi @ivanv6, I haven't considered it yet. I don't know enough about the underlying data model behind pandas to be able to tackle it directly. So far, the best and by far easiest way to operate with pandas would be to convert the columns you want to operate on into numpy arrays, perform all the operations, and convert back.

What functionality would you like to see implemented in Pyfhel regarding pandas? Is there any use case motivating your request? Would you be willing to contribute on this development or is it just a wish?

**Comment by ivanv6** [comment]
Hi @ibarrond manu thanks for your response. The idea Is ti encrypt an entire dataframe without convert into numpy and reverse. If you guide me in the procedure, i can try to contribute. Moreover, another question, Is possibile to print and encrypted numpy or variable? To see its content/value

**Comment by ibarrond** [comment]
The thing is, converting an entire pandas dataframe is extremely generic: what do you do with non numeric information? what do you do with dates? Without a more concrete objective in mind , it seems a bit hard to make it concrete.

We could try to implement the standard Pyfhel operations(encrypt/decrypt, encode/decode, add, mult, negate) for pandas.Series() with a numeric type. But again, I wouldn't go for it unless we have a clear idea of what we want to accomplish and why. Rolling out code just for the sake of writing code is not really my thing.

For the other question, can you post it in a different issue? it deserves its own attention, and I'm proud of the answer I'll give.

**Comment by ibarrond** [comment]
Surfing around pandas' documentation I found this :https://pandas.pydata.org/pandas-docs/stable/user_guide/enhancingperf.html#cython-writing-c-extensions-for-pandas

As I expected, the way they suggest you to implement fast functions with Cython is by separating a pandas dataframe into individual pandas series and converting each pandas series into numpy using `df.numpy()`. This means that, thanks to its numpy support, Pyfhel already supports Pandas series! Writing an extra Pyfhel function just to convert to numpy seems like overkill. However, this might be decent content for a new demo/example.

**Comment by ivanv6** [comment]
Amazing, so in summary the dataframe is already implement in your library! Thanks a lot! For the other question, i Will post It tomorrow with an example code! Thanks @ibarrond !

**Comment by vrush0022** [comment]
Hi...is there a way to serialize an encrypted numpy array?

**Comment by ibarrond** [comment]
Hi @vrush0022 , your question seems to be different from the encryption of a Pandas Dataframe. Can you please move it to a new issue?
