### ISSUE TITLE
How to get more noise budget in pyfhel?

### ISSUE THREAD

**Issue by vinegarg** [ibarrond/Pyfhel#64]
Hello! Thank you for your sincere help.But I got another problem that I can't get an accurate result after several multiplications.Maybe it's just as you said in Demo_MultDepth_n_relin.py，I need more noise budget.
```python
print("5. Noise budget: You can see ciphertexts as noisy signals. Every multiplication will drastically increase the noise, thus reducing the noise budget.")
print("   Notice the decrease in noise budget in the previous multiplication")
print("   If the noise budget reaches zero, we won't be able to decrypt correctly!")
print("ctxtMulsq = ctxtMult1**2")
ctxtMulsq = ctxtMul1**2
print(ctxtMulsq)
print("     decrypt(ctxtMul1) =  ", HE.decryptFrac(ctxtMul1))
print(f"      expected: {float1*float2}")
print("     decrypt(ctxtMulsq) =  ", HE.decryptFrac(ctxtMulsq))
print(f"      expected: {(float1*float2)**2}")

print("6. I need more noise budget! You have several options:")
print("  - Use better context parameters (mainly increase m, reduce p, reduce intDigits and fracDigits")
print("    -> Try this demo changing p to be 63 (enough to hold the result value) -> precision lowers, but operations are faster and noise budget decreases slower")
print("    -> Try this demo with m=8192 (more multiplications are allowed, but operations are slower)")
print("  - Decrypt and encrypt again.")
print("  - Use bootstrapping: Sadly it is not available in SEAL, and even if it were, it would be extremely inefficient. It is always better to resort to the first option")
```
As I reduce p,and increase m，such as contextGen(p=63,m=8192),it works well.But the decrypted θ(weights of logistic regression) doesn't as my expected either. The output is as follow.
```python
iters:0
[  -85.44768396  9519.0554841  -3658.87604848]
accuracy： 48.0 %
iters:1
[ 5.96169599e+18 -2.66396643e+18  3.27691186e+18]
accuracy： 46.0 %
iters:2
[ 1.62965752e+18  4.53530036e+18 -6.24380605e+18]
accuracy： 47.0 %
iters:3
[ 9.07663316e+17  9.09501187e+18 -1.34977063e+18]
accuracy： 48.0 %
iters:4
[1.61879717e+18 8.07697186e+18 1.92133730e+18]
accuracy： 52.0 %
iters:5
[ 9.07383634e+18  8.93683516e+18 -1.20579157e+18]
accuracy：51.0 %
iters:6
[ 7.85744753e+18 -3.83382664e+17  3.06473871e+18]
accuracy： 50.0 %
iters:7
[-8.36263428e+18 -4.98170861e+18  7.09412094e+18]
accuracy： 44.0 %
iters:8
[-3.52751894e+18 -1.25660778e+18  7.77091867e+18]
accuracy： 56.00000000000001 %
iters:9
[ 5.01232025e+18  4.17018339e+18 -7.28407509e+18]
accuracy： 45.0 %
iters:10
[-8.65150175e+18  5.74466247e+18  1.07196481e+17]
accuracy：54.0 %
iters:11
[ 7.43885746e+18 -7.35162442e+18 -8.00685593e+18]
accuracy： 46.0 %
iters:12
[-1.93461624e+18  2.74352768e+18 -6.20281872e+18]
accuracy： 52.0 %
iters:13
[-4.15772324e+18 -7.16728667e+18  6.12652091e+18]
accuracy： 49.0 %
iters:14
[-5.79430360e+18  2.67293372e+18 -4.38363911e+18]
accuracy： 46.0 %
iters:15
[4.98184398e+17 4.59386305e+18 9.02029985e+18]
accuracy： 50.0 %
iters:16
[-4.28819482e+18  1.34845813e+18 -5.27688052e+18]
accuracy： 48.0 %
iters:17
[-9.19862787e+18  7.40720130e+18  7.76318457e+18]
accuracy： 49.0 %
iters:18
[ 4.28263035e+18 -3.37105216e+18  2.03274195e+17]
accuracy： 48.0 %
```
Is there any other ideas to get more noise budget？Thanks for your patience very much!

**Comment by vinegarg** [comment]
for example:

import numpy as np
from Pyfhel.util import ENCODING_t
from Pyfhel import PyCtxt, Pyfhel, PyPtxt

pyfhel = Pyfhel()
pyfhel.contextGen(p=65537, m=8192, base=2, sec=192, intDigits=64, fracDigits = 32)
pyfhel.keyGen()
pyfhel.relinKeyGen(10,10)

x_enc=pyfhel.encryptFrac(0.5)
y_enc=pyfhel.encryptFrac(1.1)
xy_enc=x_enc*y_enc
pyfhel.relinearize(xy_enc)
xy_enc3=pyfhel.power(xy_enc,3,1)
pyfhel.decryptFrac(xy_enc3)//Out:0.16637498792260885  ——It's correct!

xy_enc4=pyfhel.multiply(xy_enc3,pyfhel.encryptFrac(0.04))
pyfhel.decryptFrac(xy_enc4)//Out:9.151673873493283e+18 ——But when I multiply one more time,It got a wrong result.

What should I do to make it accurate with one more multiplication after pyfhel.power()?Thank you very much!

**Comment by ibarrond** [comment]
Your best shot is to increase the parameter `m` and decrease `sec`:

```python
from Pyfhel import PyCtxt, Pyfhel, PyPtxt

pyfhel = Pyfhel()
pyfhel.contextGen(p=1964769281, m=32768, base=2, sec=128, intDigits=64, fracDigits = 32)
pyfhel.keyGen()
pyfhel.relinKeyGen(15,3)

x_enc=pyfhel.encryptFrac(0.5)
y_enc=pyfhel.encryptFrac(1.1)
xy_enc=x_enc*y_enc
pyfhel.relinearize(xy_enc)
xy_enc3=pyfhel.power(xy_enc,3,1)
pyfhel.decryptFrac(xy_enc3) #Out:0.16637498792260885  ——It's correct!

xy_enc4=pyfhel.multiply(xy_enc3,pyfhel.encryptFrac(0.04))
pyfhel.decryptFrac(xy_enc4)  #Out:0.006654957076534629  ——It's correct!
```

In general, your best weapon against noise is a good selection of parameters:
- High `m` (16384 or 32768).
- Lower `sec`(128 instead of 192).
- Lower `p` (but enough to have correct computation!).

The best way to test them is by printing the ciphertext after every operation and checking the remaining noise budget.

**Comment by vinegarg** [comment]
Thanks very much!I think I've got it.Maybe if I want deeper multiplications,I could reduce p lower (p=63？Or any other choice？)

**Comment by vinegarg** [comment]
You know,as for logistic regression,I want iters more than 12 times stocGradAscent to the weights,but it run out of noise budget only the forth time.
The parameter I set is 
contextGen(p=63,m=32768,sec=128,intGigits=64,fracDigits=32)
Thanks!

**Comment by ibarrond** [comment]
I'm afraid you might be trying to perform too many multiplications without decrypting. Unfortunately, other than playing with the context parameters, your best chance is to send some intermediate results back to the owner, decrypt them, encrypt them again, and continue the computation. Note that this limitation is inherent to Homomorphic Encryption schemes like the ones implemented in SEAL (our preferred backend).  

Additionally, if you want to know the multiplication depth of a given Pyfhel instance, you can use the following function (introduced in 3ce85c1):

https://github.com/ibarrond/Pyfhel/blob/3ce85c14f3644a8eac961092335befad3a8169a4/Pyfhel/Pyfhel.pyx#L1344


You can see an example of its usage in the [Demo_MultDepth_n_relin.py](https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_MultDepth_n_relin.py) example. Try running it!:

https://github.com/ibarrond/Pyfhel/blob/3ce85c14f3644a8eac961092335befad3a8169a4/examples/Demo_MultDepth_n_relin.py#L76-L77
