### ISSUE TITLE
sudo: add-apt-repository: command not found

### ISSUE THREAD

**Issue by AlbertoPimpo** [ibarrond/Pyfhel#66]
Building this dockerfile it's impossibile to me (i think also everywhere) because it call add-apt-repository but it doesn't have installed. In order to solve this it is enough to install software-properties-common.
I fixed this on #65 . 

P.S. Congrats for the awesome project, hope this may help

**Comment by ibarrond** [comment]
Oh nice! Thanks. Approved and merged!
