### ISSUE TITLE
Any chance to have this on arm?

### ISSUE THREAD

**Issue by AlbertoPimpo** [ibarrond/Pyfhel#68]
I tried to install this library on rpi 3b+ and it didn't compile because it lacks of x86intrin.h . There is a way in order to have it compiling successfully on arm? Maybe using a different backend of the library?

**Comment by ibarrond** [comment]
I have absolutely no idea. I'm afraid I don't have much expertise with cross compilation on

**Comment by AlbertoPimpo** [comment]
I checked the documentation of PALISADE and it officially support Nvidia Xavier that is an arm Linux board like raspberry pi using a personalized version of Ubuntu. It is also tested for each commit by their CI, so it should work. In next days I will try to compile in raspberry pi and I will know you if it works.

**Comment by ibarrond** [comment]
Looks like somebody cracked it!  #70

**Comment by AlbertoPimpo** [comment]
Great, I didn't succeed in compiling this on raspberry, now it looks like it can work

**Comment by ibarrond** [comment]
I haven't yet merged #70. Could you try it out and tell me if it works for you?

**Comment by AlbertoPimpo** [comment]
> I haven't yet merged #70. Could you try it out and tell me if it works for you?

Yes, I'll try.

**Comment by AlbertoPimpo** [comment]
@ibarrond I made a new pr (#72 ) starting from #70 in order to update dockerfile but it still doesn't work for me.
