### ISSUE TITLE
Compatibility with Numpy

### ISSUE THREAD

**Issue by vrush0022** [ibarrond/Pyfhel#69]
Hi,

I am trying to use this library in a client-cloud server scenario.
I have encrypted a numpy array using encryptArray and saved it on disk. I have also saved the public key and the context on disk.

At the cloud server end, I have restored the public key and context.
Now i load the encrypted array as below:
`enc_arr = PyCtxt(pyfhel=he_server, fileName="arr.ctxt",encoding=3)`

However when I use the numpy.sum() on this, I get below error.
```
/usr/local/lib/python3.6/dist-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    707     """A pprint that just redirects to the normal repr function."""
    708     # Find newlines and replace them with p.break_()
--> 709     output = repr(obj)
    710     for idx,output_line in enumerate(output.splitlines()):
    711         if idx:

Pyfhel\PyCtxt.pyx in Pyfhel.PyCtxt.PyCtxt.__repr__()

Pyfhel\Pyfhel.pyx in Pyfhel.Pyfhel.Pyfhel.noiseLevel()

RuntimeError: Missing a Private Key
```
I believe this library has support for using with numpy. Can you confirm?

**Comment by ibarrond** [comment]
Woops! That's a bug when calling `print(enc_arr)`! As an attempt to yield more information when printing a ciphertext (or calling its `__repr__` function as in your case), I coded Pyfhel to retrieve the noise level of a ciphertext. However, this information can only be retrieved if Pyfhel has the original Secret Key, which makes no sense in the "Server". 

I will correct this line (check if the Pyfhelinstance contains a secret key before calling `noiseLevel()`) and update this issue once it's done:

https://github.com/ibarrond/Pyfhel/blob/f4d6ad5d88eef2a9185d30579265c7c14bb55a09/Pyfhel/PyCtxt.pyx#L566

**Comment by ibarrond** [comment]
Corrected! Now you should be able to print a ciphertext without the secret key. The Numpy support is shown in this example: https://pyfhel.readthedocs.io/en/latest/_autoexamples/Demo_Numpy.html
