### ISSUE TITLE
Error while test serialize the ciphertext

### ISSUE THREAD

**Issue by allensll** [ibarrond/Pyfhel#71]
A toy example:

```
def main():
    HE = Pyfhel()  # Creating empty Pyfhel object
    p = 1964769281
    m = 8192
    assert ((p - 1) % (2 * m) == 0)
    assert (isprime(p))
    HE.contextGen(p=p, m=m, base=2, sec=192, flagBatching=True)
    HE.keyGen()

    list1 = np.array([1, 2, 3])
    list2 = np.array([2, 3, 4])

    ctxt1 = HE.encryptArray(list1)  # Encryption makes use of the public key
    ptxt2 = HE.encodeArray(list2)

    ctxt2 = PyCtxt()
    ctxt2.from_bytes(ctxt1.to_bytes(), 'array')

    ctxt2 + ptxt2
```

Error:

```
File "Pyfhel/PyCtxt.pyx", line 298, in Pyfhel.PyCtxt.PyCtxt.__add__
AttributeError: 'NoneType' object has no attribute 'add_plain'
```

**Comment by allensll** [comment]
A toy example:

```
def main():
    HE = Pyfhel()  # Creating empty Pyfhel object
    p = 1964769281
    m = 8192
    assert ((p - 1) % (2 * m) == 0)
    assert (isprime(p))
    HE.contextGen(p=p, m=m, base=2, sec=192, flagBatching=True)
    HE.keyGen()

    list1 = np.array([1, 2, 3])
    list2 = np.array([2, 3, 4])

    ctxt1 = HE.encryptArray(list1)  # Encryption makes use of the public key
    ptxt2 = HE.encodeArray(list2)

    ctxt2 = PyCtxt()
    ctxt2.from_bytes(ctxt1.to_bytes(), 'array')

    ctxt2 + ptxt2
```

Error:

```
File "Pyfhel/PyCtxt.pyx", line 298, in Pyfhel.PyCtxt.PyCtxt.__add__
AttributeError: 'NoneType' object has no attribute 'add_plain'
```

**Comment by ibarrond** [comment]
Hi @allensll. You seem to be trying to copy `ctxt1` into `ctxt2`. However, if you just copy the internal buffer, `ctxt2` has no knowledge of what Pyfhel instance to use in order to perform operations. The preferred (and fastest) way of copying a ciphertext is the following:
```python
#... 
ctxt2 = PyCtxt(copy_ctxt=ctxt1)
```
Alternatively, if for whatever reason you want to serialize it from/to bytes, you should explicitly define the Pyfhel instance to be used:

```python
# Option 1: 
ctxt2 = PyCtxt(pyfhel=HE)
ctxt2.from_bytes(ctxt1.to_bytes(), 'array')

# Option 2:
ctxt2 = PyCtxt()
ctxt2.from_bytes(ctxt1.to_bytes(), 'array')
ctxt2._pyfhel = HE
```
Nonetheless, a better error message could help. I'll add it.

**Comment by allensll** [comment]
Thanks, @ibarrond. I serialize it because I want to communicate between a client and a server. The client encrypts data and sends it to the server, then the server does some computing and returns it to the client, then the client decrypts the result.
So, how can I send the Pyfhel instance to the server？ Or any better communication method？

**Comment by ibarrond** [comment]
There is a dedicated Demo for this purpose, where the ciphertexts are saved on files prior to sending them. I suggest you use it for inspiration:
https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_ClientServer.py

It is perfectly valid to send the bytes representation instead (as the payload of a message). In this case, I encourage you to use the Option 1 from above.
