### ISSUE TITLE
Add WIP action in order to make impossible to accept incomplete or not working PR 

### ISSUE THREAD

**Issue by AlbertoPimpo** [ibarrond/Pyfhel#73]
It can be helpful show what you are working on with a PR before is finished (like i did with #72 ) but if it is incomplete it can be mistaken as ready and merged. With an action like WIP action PRs that contains WIP in the name will be unmergeble.

**Comment by ibarrond** [comment]
Although I understand your request, I don't know how to put it in practice.

I do use [`travis`](https://travis-ci.org/github/ibarrond/Pyfhel/) with a [.travis.yml](https://github.com/ibarrond/Pyfhel/blob/master/.travis.yml) for automated tests on a Linux OS, but I wouldn't know how to detect and filter the name of the PR in question (this Travis action is triggered by either all PR or None).

I've never played with Github Actions myself. Do you happen to know how to achieve this?

**Comment by AlbertoPimpo** [comment]
I will do a PR for this

**Comment by ibarrond** [comment]
Closing as it is stale. Can be reopened if there is activity.
