### ISSUE TITLE
Pyfhel Encoding and Decoding Bug

### ISSUE THREAD

**Issue by marwah89** [ibarrond/Pyfhel#76]
The  _from_bytes_ function shows this error:
TypeError: descriptor 'from_bytes' requires a 'Pyfhel.PyCtxt.PyCtxt' object but received a 'bytes'
when trying to decode an encoded PyCtxt object.
While the task of  from_bytes  is to recover the PyCtxt ciphertext from a bytes string. So, it must accept PyCtxt and not byte.
Below is a simple example of the _to_bytes_ and _from_bytes_ I used. Is it a bug or I use it wrongly?
```python
from Pyfhel import Pyfhel, PyPtxt, PyCtxt
homomorphic = Pyfhel()

def initilization(long_p):
    if homomorphic.is_context_empty():
        homomorphic.contextGen(long_p)
        homomorphic.keyGen()
        return None

def encryption(num):
    initilization(65537)
    encoded_num = homomorphic.encodeInt(num)
    return homomorphic.encrypt(encoded_num)

r1 = encryption(4)
print("encrypted Data: ",r1)
br1 = PyCtxt()
br1 = PyCtxt.to_bytes(r1)
print("Encoded with to_bytes: ", br1)
fr1 = PyCtxt()
fr1 = PyCtxt.from_bytes(br1)
print("decoded with from_bytes ", fr1)
```

**Comment by ibarrond** [comment]
You just need to call the `from_bytes()` function of your `fr1` ciphertext instead of the generic one from the `PyCtxt` class:

```python
#... 
fr1 = PyCtxt()
fr1.from_bytes(br1, encoding='int')
print(homomorphic.decryptInt(fr1))
#> 4
```
I will consider adding an example about serialization.

**Comment by marwah89** [comment]
Thanks for the comment. I decode it by your way.
But in fact, I still get the issue while sending to the server. 

#The client code

from __future__ import print_function, unicode_literals
import socket
from pip._vendor.distlib.compat import raw_input
from Pyfhel import Pyfhel, PyPtxt, PyCtxt

he = Pyfhel()

def initilization(long_p):
    if he.is_context_empty():
        he.contextGen(long_p)
        he.keyGen()
        return None

def encryption(num):
    initilization(65537)
    encoded_num = he.encodeInt(num)
    enc_num1 = he.encrypt(encoded_num)
    return enc_num1

def decryption(encrypted_result):
    dec_result = he.decrypt(encrypted_result)
    decoded_result = he.decodeInt(dec_result)
    return decoded_result

client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

r1 = encryption(4).to_bytes()
print("PyCtxt encoded: ", r1)

fr1 = PyCtxt()
fr1.from_bytes(r1, encoding='int')
print("PyCtxt Decoded: ", fr1)
print("Decrypted: ", he.decryptInt(fr1))

client_socket.connect(('192.168.1.67', 1234))
client_socket.sendall(r1)
res = decryption(client_socket.recv(33048)).decode()
print(res)
     
client_socket.close()

#The server code 
import socket
from Pyfhel import Pyfhel, PyPtxt, PyCtxt
import random
import base64
import tempfile

he = Pyfhel()

server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_socket.bind(('192.168.1.67', 1234))
server_socket.listen(1)
print("listening")
client_socket,addr = server_socket.accept()
print("Got a connection")

while True:
    res = client_socket.recv(33048)
    print("Recieved Bytes: ", res)
    
    fr1 = PyCtxt()
    fr1.from_bytes(res, encoding='int')
    print("PyCtxt Decoded: ", fr1)
    print("Decrypted: ", he.decryptInt(fr1))
    
server_socket.close()

Please can you take a look at this code

**Comment by ibarrond** [comment]
Can you develop further? What error are you getting and where? 

What is your setup? (OS, Python version, Pyfhel version).

**Comment by marwah89** [comment]
Here is a simple code to send an encoded PyCtxt from client to server using socket and decrypt it in the server.

**#The server code**
import socket
from Pyfhel import Pyfhel, PyPtxt, PyCtxt
he = Pyfhel()
server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_socket.bind(('192.168.1.67', 1234))
server_socket.listen(1)
print("listening")
client_socket,addr = server_socket.accept()
print("Got a connection")
while True:
---res = client_socket.recv(33048)
---print("Recieved Bytes: ", res)
---fr1 = PyCtxt()
---fr1.from_bytes(res, encoding='int')
---print("PyCtxt Decoded: ", fr1)
---print("Decrypted: ", he.decryptInt(fr1))
server_socket.close()

**#The client code**
from future import print_function, unicode_literals
import socket
from pip._vendor.distlib.compat import raw_input
from Pyfhel import Pyfhel, PyPtxt, PyCtxt
he = Pyfhel()

def initilization(long_p):
---if he.is_context_empty():
------he.contextGen(long_p)
------he.keyGen()
------return None

def encryption(num):
---initilization(65537)
---encoded_num = he.encodeInt(num)
---enc_num1 = he.encrypt(encoded_num)
---return enc_num1

def decryption(encrypted_result):
---dec_result = he.decrypt(encrypted_result)
---decoded_result = he.decodeInt(dec_result)
---return decoded_result

client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
r1 = encryption(4).to_bytes()
print("PyCtxt encoded: ", r1)
fr1 = PyCtxt()
fr1.from_bytes(r1, encoding='int')
print("PyCtxt Decoded: ", fr1)
print("Decrypted: ", he.decryptInt(fr1))
client_socket.connect(('192.168.1.67', 1234))
client_socket.sendall(r1)
client_socket.close()

The decoding is not working after sending the bytes to the server, these are the execution screenshot:
Server:
![s](https://user-images.githubusercontent.com/56391407/101656237-c6a6ba00-3a42-11eb-8d02-c4b8a6c492b5.png)

Client: 
![c](https://user-images.githubusercontent.com/56391407/101656263-cc9c9b00-3a42-11eb-960d-a40c912c4823.png)

I use Windows 10, Python 3.7.7, Pyfhel 2.2.4

**Comment by marwah89** [comment]
Its because of that _rsv_ encoding is undefined. her is the variable _rsv_ printed:

<Pyfhel Ciphertext at 0x2bc0026a8b8, encoding=UNDEFINED, size=2/2, noiseBudget=->

Now how to change its encoding?

**Comment by ibarrond** [comment]
Please check if the `rsv` object contains what seems to be a ciphertext (just print the first 10 characters before and after sending the bytes object).

**Comment by nshStr** [comment]
> You just need to call the `from_bytes()` function of your `fr1` ciphertext instead of the generic one from the `PyCtxt` class:
> 
> ```python
> #... 
> fr1 = PyCtxt()
> fr1.from_bytes(br1, encoding='int')
> print(homomorphic.decryptInt(fr1))
> #> 4
> ```
> 
> I will consider adding an example about serialization.

Thanks, the encoding works.
