### ISSUE TITLE
Error in installing pyfhel related to numpy

### ISSUE THREAD

**Issue by hedibouattour** [ibarrond/Pyfhel#77]
i've tried to install pyfhel but got this error.

{
 File "setup.py", line 165, in finalize_options
        import numpy
      File "C:\Users\hedi bouattour\AppData\Local\Temp\pip-build-env-l46ewvsx\overlay\Lib\site-packages\numpy\__init__.py", line 305, in <module>
        _win_os_check()
      File "C:\Users\hedi bouattour\AppData\Local\Temp\pip-build-env-l46ewvsx\overlay\Lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
        raise RuntimeError(msg.format(__file__)) from None
    RuntimeError: The current Numpy installation ('C:\\Users\\hedi bouattour\\AppData\\Local\\Temp\\pip-build-env-l46ewvsx\\overlay\\Lib\\site-packages\\numpy\\__ini
t__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
    ----------------------------------------
}

I already tried to install an older version of numpy (1.19.3) but the error persists

**Comment by ibarrond** [comment]
Yeap, this installation error comes from NumPy itself. You can google it to understand it further, as it appeared with the last Windows 10 update. As a temporal workaround, I suggest you to use WSL in Windows 10. They claim it will get solved in the following months

**Comment by ibarrond** [comment]
Looks like PyfhelV3 (#122) should have this solved!
