### ISSUE TITLE
Client-server HE addition

### ISSUE THREAD

**Issue by nshStr** [ibarrond/Pyfhel#78]
I am trying to send encrypted numbers from the client to the server, the server adds then homomorphically using Pyfhel, then returns the result to the client to decrypt it.
I am getting a wrong shaped PyCtxt from on the client-side. bellow is the code:

Client Code:
```python
import socket
from Pyfhel import Pyfhel, PyPtxt, PyCtxt

he = Pyfhel()
he.contextGen(65537)
he.keyGen()
s = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
s.connect(('127.0.0.1',12345))

n1 = he.encrypt(5).to_bytes()
ans = 0
while True:    
    s.send(n1) 
    n1 = he.encryptInt(4).to_bytes()
    data = s.recv(33048)
    if ans < 1: 
        ans = ans + 1
        continue
    else:
        sumr = PyCtxt()
        sumr.from_bytes(data, encoding='int')
        print('Received from the server :',he.decrypt(sumr))
        break
    s.close()
```
Server Code:
```python
import socket 
from _thread import *
import threading
from Pyfhel import Pyfhel, PyPtxt, PyCtxt

he = Pyfhel()
he.contextGen(65537)
he.keyGen()
print_lock = threading.Lock() 
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM) 
s.bind(('127.0.0.1', 12345)) 
s.listen(5)

h = 0
c1 = PyCtxt()
c2 = PyCtxt()
c3 = PyCtxt()
while True:
    c, addr = s.accept() 
    print_lock.acquire() 
    while True:
        data = c.recv(33048)
        if h == 0:
            c1.from_bytes(data, encoding='int')
            h = h + 1
        elif h == 1:
            c2.from_bytes(data, encoding='int')
            h = h + 1
            b = False
            c3 = he.add(c1, c2, b)
        c.send(c3.to_bytes())
    c.close()
s.close() 
```
I am getting this on the client:
<Pyfhel Ciphertext, encoding=INTEGER, poly=>
which can't be decrypted.

**Comment by ibarrond** [comment]
There seems to be some issue with the `decrypt` method. I tried your code and managed to reproduce the error. The easiest solution is to use the `decryptInt` method instead. It worked for me:

```python
# Code above, 2 terminals [...] -> Substitute decrypt with decryptInt
Received from the server : 9
```

**Comment by ibarrond** [comment]
Ok, there was some mistake in the code! when using the `decrypt` method, you must use `decode_value=True` to obtain a decoded integer/float, otherwise you get a PyPtxt encoded plaintext (just like in your code). The mistake in the code was printing the result of the decryption as a "Ciphertext" instead of  a "Plaintext". dc077a9 solved it.

**Comment by nshStr** [comment]
> Ok, there was some mistake in the code! when using the `decrypt` method, you must use `decode_value=True` to obtain a decoded integer/float, otherwise you get a PyPtxt encoded plaintext (just like in your code). The mistake in the code was printing the result of the decryption as a "Ciphertext" instead of a "Plaintext". [dc077a9](https://github.com/ibarrond/Pyfhel/commit/dc077a93a4358d801d28992795530b134478b2c7) solved it.

Thank you very much Ibarrond!
