### ISSUE TITLE
How do I get public key?

### ISSUE THREAD

**Issue by tdonovic** [ibarrond/Pyfhel#8]
Is there a way to get a copy of the public key so I can send it to another party to have them encrypt the data I want to compute?

**Comment by tanu17** [comment]
@tdonovic can you share your method to overcome the error in the makefiles-
Afhel.cpp:50:14: error: definition of implicitly-declared ‘Afhel::Afhel()’
 Afhel::Afhel(){}

**Comment by ibarrond** [comment]
Yes it is! With the fresh new version of the library you can save and restore both public and private keys, as well as plaintexts and ciphertexts. You can then send them however you see fit

**Comment by ibarrond** [comment]
FYI: the example [Demo_ClientServer.py](https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_ClientServer.py) showcases this exact functionality.
