### ISSUE TITLE
How to avoid passing Pyfhel object to a function as an argument?

### ISSUE THREAD

**Issue by helplesshell** [ibarrond/Pyfhel#82]
Hello everyone!
I'm brandly new to Pyfhel. I'm structuring a main script where I import a function from another script. I have to pass the function encrypted data as arguments, and the function has to manipulate such data.
The question is: there's a way to use Pyfhel methods (such as add(...), multiply(...), sub(...), ecc) in the function's script without passing the Pyfhel object? The goal is to preserve privacy, so if I pass the Pyfhel object to the function, there the savesecretKey(...) method could be used , and I'm trying to avoid it.

I'm preparing my Bachelor Thesis in Homomorphic Encryption, and this could really help me.
Do you have any tips for me?
Thanks.

**Comment by ibarrond** [comment]
To make it cleaner, I strongly suggest you to create a new Pyfhel object, just like in the [Demo_ClientServer.py](https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_ClientServer.py).

In this demo you can see how to create a completely independent second Pyfhel object (`HE_Cl` in the demo) and load both the Public Key (required to encrypt new data) and the context (required to perform operations). Since this second Pyfhel object is not loading any secret key, if anyone tried to call the `savesecretKey()` function, they would get an exception `"<Pyfhel ERROR>: Missing a secret key"`.

What do you think?

**Comment by helplesshell** [comment]
Well, the idea seems to accomplish the goal.
But I don't know if it's because of my incompetence or what, but it doesn't seem like working.
I tried to do simple operations, for example 5*5, but the result decrypted turns out to be like -2.9919460677213793e+18. I didn't expect to be perfect, but neither so bad. 
I don't know where I'm doing wrong.

I really appreciate your help, thank you for your availability.

**Comment by helplesshell** [comment]
> To make it cleaner, I strongly suggest you to create a new Pyfhel object, just like in the [Demo_ClientServer.py](https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_ClientServer.py).
> 
> In this demo you can see how to create a completely independent second Pyfhel object (`HE_Cl` in the demo) and load both the Public Key (required to encrypt new data) and the context (required to perform operations). Since this second Pyfhel object is not loading any secret key, if anyone tried to call the `savesecretKey()` function, they would get an exception `"<Pyfhel ERROR>: Missing a secret key"`.
> 
> What do you think?

**Comment by ibarrond** [comment]
I don't know what parameters are you using (maybe you need stronger parameters). Can you share your code so that we can diagnose your problem?

**Comment by helplesshell** [comment]
I noticed that the problem is not about passing pyfhel object as a parameter to a function, but using pyfhel.multiply or pyfhel.power functions. I read in the documentation that relinKeyGen() is required before each multiplication, because of the increasing noise. With the following code I noticed that for exponents <= 2 everything works, but for the others not.
I thought it was because it's needed to relinearize the key and the cyphertext before every multiplications, and for an exponent=2 there's only one multiplication to do.

`he.relinKeyGen(6,cr_b.size()+1)
 he.relinearize(cr_b)
  cr_result = he.power(cr_b,e)  `

where:
- "he" is the pyfhel object;
- "cr_b" is a PyCtxt object;
- "e" is an integer.

**Comment by helplesshell** [comment]
I also tried in this way, but same problem.


`
                            cr_result = he.encryptFrac(1)
                            counter = e
                            
                            while (counter >= 1):
                                he.relinKeyGen(6,cr_result.size()+1)
                                he.relinearize(cr_result)
                                he.relinearize(cr_b)
                                cr_result = he.multiply(cr_result, cr_b) 
                                counter = counter - 1
                 
                                
                            dcr_result = he.decryptFrac(cr_result)`

**Comment by helplesshell** [comment]
I also tried in the following way, but same problem.


`cr_result = he.encryptFrac(1)
while (counter >= 1):
                            he.relinKeyGen(6,cr_result.size()+1)
                            he.relinearize(cr_result)
                            he.relinearize(cr_b)
                            cr_result = he.multiply(cr_result, cr_b) 
                            counter = counter - 1
             
                            
                        dcr_result = he.decryptFrac(cr_result)`

**Comment by helplesshell** [comment]
I also tried in the following way, but same problem.

                  ` cr_result = he.encryptFrac(1)
                     while (counter >= 1):
                                        he.relinKeyGen(6,cr_result.size()+1)
                                        he.relinearize(cr_result)
                                        he.relinearize(cr_b)
                                        cr_result = he.multiply(cr_result, cr_b)
                                        counter = counter - 1

                    dcr_result = he.decryptFrac(cr_result)`

**Comment by ibarrond** [comment]
Relinearization is not required but greatly encouraged to keep a small size of the ciphertexts. The noise (which is causing your weird results) comes from running several multiplications. Take a look at #64 to see tips on how to get more noise budget. Anyhow, the numerical errors are not related to the question of this issue. If you're still struggling, please open a new issue with your question. 

I'll close this issue keeping in mind that you should create different Pyfhel objects to isolate parts of your code and pass them to a function argument.

**Comment by helplesshell** [comment]
Ok, I'll take a look at #64 .
Thanks a lot for your help!
