### ISSUE TITLE
How to extract sign of Ciphertext?

### ISSUE THREAD

**Issue by vrush0022** [ibarrond/Pyfhel#85]
I would like to find out the greater of the 2 ciphertext. As comparison operation is not possible, I would like to know how to extract the sign from the operation (Ca-Cb).

**Comment by ibarrond** [comment]
I'm afraid both things are equivalent. Comparison between integers is actually performed by extracting the MSB (sign bit) from its subtraction. Take a look at #80 for a few alternatives. This bit extraction would also be similar to #56 .
