### ISSUE TITLE
CuPy support

### ISSUE THREAD

**Issue by comidan** [ibarrond/Pyfhel#86]
Hello!

Just wanted to ask whether was possible, or if it was already present in the todo list, to introduce compatibility with CuPy (it's the GPU equivalent version of NumPy, it even uses some NumPy dtypes) in order to have an increase in time performance for the various operations on encrypted data.
I tried to run the [example](https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_Numpy.py) provided in your repository but while in NumPy everything goes fine indeed, using CuPy it raises the exception of unsupported dtype.

They are pratically equivalent in each method, CuPy just automatically transfer all computation to the available GPU. Unfortunately I never tried to add support for a specific library, so if it's way more complex and time consuming than what it seems (even with CuPy being equivalent to NumPy) then it's no problem.

Thank you!

**Comment by ibarrond** [comment]
Hi @comidan , unfortunately this is not possible. Pyfhel can use NumPy to encapsulate vectorized operations, but the underlying operations depend on SEAL, which is written in C++ with its own classes. 

Redevelopping SEAL to have it based completely on NumPy and then porting it to CuPy is a titanical task that I'm not up to for the time being.

**Comment by comidan** [comment]
Thank you for the quick response. I fully understand, yes that would be a very large task indeed.

I quickly checked now on SEAL repository feature request and even they are not going to.
They said they tried to add CUDA support and also run some performance test comparison but sadly it seems this feature has been dropped.
