### ISSUE TITLE
How to make cyphertext comparisons using Pyfhel?

### ISSUE THREAD

**Issue by tiphainehenry** [ibarrond/Pyfhel#89]
Hello, 

I am looking for a way to do cyphertext number comparisons using python. 
The usual way to do it is to implement boolean circuits comparisons, and C++ libraries such as THFE propose this feature (https://tfhe.github.io/tfhe/tuto-cloud.html). 
I did not find any python-related implementations. Is there a way to do it using Pyfhel?

I am interested in implementing FHE proprieties in the context of online marketplaces, as part of my PhD project.

Thank you for your help and advice!
Best,
Tiphaine

**Comment by ibarrond** [comment]
Hi @tiphainehenry I'm afraid the backend library SEAL is using  FHE schemes (BGV/BFV/CKKS) that are not compatible with bit level comparisons, as it is the case with TFHE. As such, to perform comparisons with them you need to resort to alternative methods. Have a look at #80 for some options.

If you absolutely need to do this in FHE, then I suggest you to use [concrete](https://github.com/zama-ai/concrete).

**Comment by tiphainehenry** [comment]
Dear ibarrond, thank you for the tip! Did you use any automatic library to do the c++/python bindings for the SEAL library?

**Comment by ibarrond** [comment]
Nope, Pyfhel uses a manually written C++ layer on top of SEAL, and then uses Cython to bridge between C++ and Python. Sadly, nothing automatic.
