### ISSUE TITLE
How to [feature]?

### ISSUE THREAD

**Issue by jackieCHJ** [ibarrond/Pyfhel#91]
when i use Pyfhel with import 'from Pyfhel import Pyfhel, PyPtxt, PyCtxt'
show:
ImportError: cannot import name 'PyPtxt' from 'Pyfhel' (...\Pyfhel-master\Pyfhel\__init__.py)

**Comment by ibarrond** [comment]
Please, fill the information related to a bug. I'll try my best to help you.

**Comment by ibarrond** [comment]
Please reopen by filling all the information requested in the bug report so that we can better understand what happened.
