### ISSUE TITLE
Pyfhel CONTEXT PARAMETERS

### ISSUE THREAD

**Issue by hebabaze** [ibarrond/Pyfhel#94]
Even if I read the documentation available on Pyfhel, I did not understand the parameters of "**contextGen**".
which what i need modified if i want to change private and public key size, to make them as 64B or 128B as an example

**Comment by ibarrond** [comment]
In order to select the key size you should use the `sec` parameter. Note that only 128bit and 192bit are available.

**Comment by hebabaze** [comment]
thanks and what about the maximal size of encrypted data ?

**Comment by ibarrond** [comment]
There is no parameter to control that, I'm afraid.

**Comment by hebabaze** [comment]
**Thank You**

**Comment by ibarrond** [comment]
closing!
