### ISSUE TITLE
Does encryptBatch support fixed point number?

### ISSUE THREAD

**Issue by ziyao002** [ibarrond/Pyfhel#95]
Hi noticed that encodeBatch and encryptBatch can be used for integers, I was wondering if these two functions support fixed-point numbers (fractional numbers)? Besides, which FHE scheme used as the building block of Pyfhel? BFV or CKKS? Thank you so much in advance!

**Comment by ibarrond** [comment]
I'm afraid they don't. The FHE scheme implemented so far is a BFV variant (hence the lack of fixed-point support). CKKS support was envisioned, but I never found the time to include it.

**Comment by ziyao002** [comment]
> I'm afraid they don't. The FHE scheme implemented so far is a BFV variant (hence the lack of fixed-point support). CKKS support was envisioned, but I never found the time to include it.

Understand, thank you!

**Comment by ibarrond** [comment]
CKKS support is coming! stay tuned, as in less than 1 month we should have it here.
