### ISSUE TITLE
How to display ciphertext in readable format?

### ISSUE THREAD

**Issue by rkarn** [ibarrond/Pyfhel#96]
**Describe the feature**
I run the example given at https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_Float.py  . I want to display the content of variable ctxt1 and ctxt1 .  Currently, it prints as <Pyfhel Ciphertext at 0x7fa51a934240, encoding=FRACTIONAL, size=2/2, noiseBudget=28>  .    

How to display it in numbers. e.g. the plain text is -7.3.  What is the value after encryption?

**Comment by ibarrond** [comment]
**How?** If you absolutely need to check the contents of the ciphertext, you can call `ctxt1.to_bytes()`, which prints the entire ciphertext (warning, it is large even for individual values!)

```python
from Pyfhel import *
he = Pyfhel()
he.contextGen(100)
he.keyGen()
ctxt1 = he.encryptFrac(7.3)
print(ctxt1.to_bytes())
#> b'\xd6\xf2\x85\x86+E\x87\x1ds\xfa\xc1^\x0eB\x94\x8a<\xbf\xc0X\xa7m\x07\x8d\x0e\x10\
#   xe9\xa1\xd6\n\xb3\x8b\x02\x00\x00\x00\x01\x08\x00\x00\x01\x00\x00\x00\xcaT\x8eK\xcd\xc3:
#   \x00\x9d\xec\x0e\xf4.\xd7)\x00\xd9\x8f\x07\xce0*(\x00\xf7\xd1XR\x91v/\x00\xb56\xf2o\xf9\x83
#   \x08\x00\xd5Q\x93\xe1\xa5m\x15\x00\x0cxx\xaa\xbc\xa2.\x00\x1bJ;d\x18\x83\x03\x00c\x1d9
#   \xff\xf6g8\x00\'6\xd0\xc2-b:\x00\xa9fk\xd3\xa5\x1d<\x00J\x12A\xb3\x12\xe7\x1d\x00\xeb\xe3|
#   \xfc\xfa88\x00\x139ut\xb7\xdf\n\x00\x8f\xf4\xda\x19\\U\x1b\x00\xf7a9\xff\xe6c(\x00\x8e\x9c~
#   \xfdP\x19\x00\x00\x1b\x99J\x...
```


**Why?** There is actually no point on printing this. As expected from an encrypted value, the ciphertext looks like complete and absolute gibberish. The only important information about the ciphertext is already shown when calling `print(ctxt1)`.
```python
print(ctxt1)
#> <Pyfhel Ciphertext at 0x7f715586b240, encoding=FRACTIONAL, size=2/2, noiseBudget=38>
```

**Comment by rkarn** [comment]
I want to do homomorphic computation on FPGA. So, I had understanding that cipher text will be numeric and the value of cipher text is dependent on the key pair size (number of bits).   So, is it possible to display the cipher text numerically?

**Comment by ibarrond** [comment]
I see. Sadly, Pyfhel doesn't have access to the underlying numbers, only the high level serialization presented above. If you wish to access the internal polynoms/matrices, and considering you'll be implementing it in an FPGA, I strongly suggest you to move to **C language** and use [SEAL](https://github.com/microsoft/SEAL/).

**Comment by ibarrond** [comment]
Forget what I said! A recent update will expose the internal numerical values of ciphertexts, plaintexts and keys as vectors/arrays/lists of complex values. Stay tuned!

**Comment by pogevip** [comment]
> Forget what I said! A recent update will expose the internal numerical values of ciphertexts, plaintexts and keys as vectors/arrays/lists of complex values. Stay tuned!

@ibarrond So, how to display the cipher text numerically now?
